### ISSUE TITLE
Add organisation option should not be presented to a user who is not a SuperAdmin

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#100]
1. Logged in as MSFTAdmin (Org Admin user)
2. Went to https://ckanfrontend.cloudapp.net/dashboard/organizations
3. Noticed Add Organisation button
   ![image](https://cloud.githubusercontent.com/assets/7315913/3844580/99a48c3c-1e4a-11e4-8fa9-08d675034e9e.png)
4. Although the created organisation does get rejected by the platform, this option should still not be presented to non SuperAdmins.

**Comment by mcginns** [comment]
This option is now not available to non-super admin users
