### ISSUE TITLE
'My datasets' link doesn't list the datasets that I have write access on

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#102]
While logged in as MSFTAdmin, i go the dashboard and click on My datasets tab
The page is empty. Ideally it should list all the datasets within my organisation.
![image](https://cloud.githubusercontent.com/assets/7315913/3857454/785d5928-1f03-11e4-8da1-c96e391ed7ff.png)

**Comment by mcginns** [comment]
This is similar to 183 and relates to how the harvester assign an owner to the dataset or resource created. All user created resources seems to have a default owner.

Flagging as P1 so we can consider with 183....we could probably merge these issues.

**Comment by mcginns** [comment]
Have moved issue details into #183 as this is a slightly different manifestation of the same issue.
Closing.....
