### ISSUE TITLE
[8] Message on screen after creating Organisation is incorrect

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#105]
After creating an organisation, the message displayed on screen says "Creation of Dataset" has been requested. NEeds to change

![image](https://cloud.githubusercontent.com/assets/7315913/3892822/8204cb3e-2235-11e4-8c79-d032b6cb123f.png)

**Comment by adamamyl** [comment]
infer from CKAN. Add org/user/dataset etc.

**Comment by Nithyavasudevan** [comment]
message now correct
