### ISSUE TITLE
Unable to upload any more files after one is uploaded

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#110]
1. Created a dataset called 'Upload Defect'
2. Uploaded a file to it using the 'Why not add some' link
3. File still in pending status and i can see the 'Why not add some' link using which i can presumably upload another file.
4. Now uploaded a file to the same dataset via the test tool ('via testtool')
5. After this file got harvested back to ckan frontend, noticed that the file upload button is no longer available

![image](https://cloud.githubusercontent.com/assets/7315913/3955668/bc1ee8e0-2703-11e4-9659-e35a0f804579.png)

**Comment by adamamyl** [comment]
if creation date is added, uploads work.

**Comment by adamamyl** [comment]
Ideally before 2014-08-21

**Comment by amercader** [comment]
@Nithyavasudevan The "Why not add some" link is just a helper for where there are no resources on the dataset. The way to add new resources regardless of how many existing ones there are is via "Manage" > "Resources" tab > "Add new Resource"

**Comment by Nithyavasudevan** [comment]
That makes sense!! Thanks!!

**Comment by Nithyavasudevan** [comment]
REtested. Works fine.
