### ISSUE TITLE
[7] Value 0 for Quality is replaced with null in file metadata

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#111]
Uploaded a file with metadata for Quality as 0. However, when trying to fetch it back, it shows as null in ckan screen

![image](https://cloud.githubusercontent.com/assets/7315913/3955830/5216d672-2705-11e4-833d-1fc7bd41ade0.png)
![image](https://cloud.githubusercontent.com/assets/7315913/3955852/8dc5b10c-2705-11e4-9902-e0e444e63a98.png)

**Comment by amercader** [comment]
There's still some cases when this can failed, we'll look into it

**Comment by Nithyavasudevan** [comment]
works
