### ISSUE TITLE
File metadata not listing many values

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#112]
When exploring a file to look at its metadata, noticed the following values are not being fetched back

Standard Version
Type
 and license not listing the actual value. it shows up as null.
![image](https://cloud.githubusercontent.com/assets/7315913/3955919/21829004-2706-11e4-9181-ae0818fa9259.png)
![image](https://cloud.githubusercontent.com/assets/7315913/3955932/3791e9d0-2706-11e4-8deb-93a7ea1a3381.png)

**Comment by adamamyl** [comment]
Ideally fixed by 2014-08-21, so I5 can be signed off.

**Comment by amercader** [comment]
Fixed and deployed to integration.
- Standard version was not rendered on the frontend
- License expected a license id like the ones provided on the form, which is not always the case. Updated to display the value as is.
- Type is called Format in CKAN

https://ckanfrontend.cloudapp.net/dataset/jde-dataset-2-a5ee/resource/7abbbe76-98a1-43e9-bf3e-4a2432661811

**Comment by Nithyavasudevan** [comment]
working
