### ISSUE TITLE
Unable to add user to organisation

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#113]
Logged in as superadmin1
Went to manage screen for organisation Peoplesoft.
Tried to add user 1dfee975-f744-4d48-a870-f20d00683111 as admin.
Got error.
![image](https://cloud.githubusercontent.com/assets/7315913/3958102/39a3c002-271c-11e4-85e6-ca01cab1f423.png)

**Comment by adamamyl** [comment]
This is associated with the "username being null" CTPEC error, that we're trying to resolve…

**Comment by Nithyavasudevan** [comment]
can we manually add one username to your db so we can test this until MS provide a fix?

**Comment by joetsoi** [comment]
I'm just to sum up why this is occuring.

when you try to add an editor/admin to an organization. Ckan will try and fetch the EC user using the username that it currently contains. This will fail, as Ckan currently stores the username as the userid from ckanext-oauth2waad. 

If a user does not exist, ckanext-oauth2waad will create the user and currently stores the user_id as the username as the oauth2token only gives these details in it's response see Access Token Response http://msdn.microsoft.com/en-us/library/azure/dn645542.aspx

So to correct this, we will be fetching the usernames at the start when we clean out the database, there is a command 'get_users' to do a one off sync of users that will fetch usernames, emails, etc so the ckan user table is correctly populated. This is currently broken as the platform Identity API is not returning user details.

The end result is that ckan will not let you add users as admins or editors.

**Comment by adamamyl** [comment]
Needs user roles and perms in place (see #53)

**Comment by joetsoi** [comment]
when #166 is deployed, the pending members should appear in that tab, otherwise adding a member should be working

**Comment by Nithyavasudevan** [comment]
works
