### ISSUE TITLE
Unable to add file version

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#115]
There is no link to add versions to file.
![image](https://cloud.githubusercontent.com/assets/7315913/3983450/19f70020-287f-11e4-98da-31c898ebe7ea.png)

**Comment by adamamyl** [comment]
See #32

**Comment by joetsoi** [comment]
it's on staging now eg https://okfstagingfe.cloudapp.net/dataset/ee3e5f14-f6e5-42de-b818-42eea0e2547a/resource/2894dcb7-4b98-447c-a281-fd1b1fcdb624/version/new it'll be in the next deployment to integration

**Comment by amercader** [comment]
To access the form there is a link in the resource actions and a button on the Versions page:

![izdxcwa](https://cloud.githubusercontent.com/assets/200230/4089702/5c34ff3e-2f71-11e4-9b37-a095e8f51ea7.png)

![r1pu79f](https://cloud.githubusercontent.com/assets/200230/4089703/5c3861ce-2f71-11e4-915c-4dfe4ef98299.png)

**Comment by Nithyavasudevan** [comment]
able to add version now.
