### ISSUE TITLE
[5] CKAN url's not consistent in many pages

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#116]
The url displayed on CKAN for different datasets seems to be in different formats.

Eg. Dataset - JDE Dataset 2
url - https://ckanfrontend.cloudapp.net/dataset/jde-dataset-2-a5ee

The last 4 characters in the url are the first 4 characters from the Org ID GUID

Eg2. Dataset - eriufhb weiufh
url - https://ckanfrontend.cloudapp.net/dataset/eriufhb-weiufh

No GUID.

**Comment by adamamyl** [comment]
Happens when duplicate names.

Likely to be search index not cleared, or duplicate. Only 4characters in dataset

**Comment by amercader** [comment]
Check updates as well

**Comment by Nithyavasudevan** [comment]
Will keep an eye on this for some time

**Comment by Nithyavasudevan** [comment]
seems ok
