### ISSUE TITLE
CKAN url to display names rather than GUID

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#118]
The url for CKAN pages seem to include the guid for each resource rather than name. Can this include the names instead?

![image](https://cloud.githubusercontent.com/assets/7315913/3988591/f536b014-28b0-11e4-9a94-9db4a1b3591a.png)

**Comment by mcginns** [comment]
URLs seem ok for standard datasets and resources, when visiting versions of resources the formatting of urls seems to change to include guids
