### ISSUE TITLE
Manage button in file page sends incorrect org details

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#119]
Clicking on manage button in the file page and updating metadata seems to pass a json with data that doesn't exist on the platform.
This is the message i got from platform
Message - File metadata 'nn v2' ('', version 'f4f7159f-4256-4561-bdc6-1d5fc3a1f774') was not updated - 'File Id : 07d1ae9a-e44a-457e-a5ed-5d55c129423d, Version: f4f7159f-4256-4561-bdc6-1d5fc3a1f774 for Organisation Id :25e709f1-d935-4146-ad88-9589aa647778, DataSet:f8c84440-24c6-40ce-a0b0-eafacd15ac59 does not exist in System.'.

![image](https://cloud.githubusercontent.com/assets/7315913/3997869/040a8b00-2943-11e4-9a23-aea9c156e9ea.png)

![image](https://cloud.githubusercontent.com/assets/7315913/3997899/5cdab8cc-2943-11e4-9863-3710baff7e2d.png)

**Comment by amercader** [comment]
This seems to be an issue with this particular file.

First of all CKAN is sending the right parameters, the message returned by the platform has the Org id and Dataset id the wrong way around, which causes confusion.

The org and the dataset exist in the platform, but not this particular file:

https://gccctpecmetadataservicesint.cloudapp.net/Metadata/Organisation/f8c84440-24c6-40ce-a0b0-eafacd15ac59/Dataset/25e709f1-d935-4146-ad88-9589aa647778/File

Looking at the changelog, there is only an entry for file 07d1ae9a-e44a-457e-a5ed-5d55c129423d, which is the CreateFile command which happened on 2014-08-20T16:53:46.1167143Z.

There is no further entry in the changelog for the file or its version (f4f7159f-4256-4561-bdc6-1d5fc3a1f774), eg a deletion that could explain why it's not there any more.

As far as CKAN is concerned that file still exists on the platform. It probably was deleted internally somehow in a way that the changelog was not notified.

I suggest trying other files to see if this is a general behaviour.

Edits in other files (existing in the platform) work fine:
https://ckanfrontend.cloudapp.net/request/95b8feb3-4bfd-4a16-94c5-1088b602bf77
https://ckanfrontend.cloudapp.net/dataset/test-tr/resource/8e22da49-d349-497e-8bbc-3f7df33d1bdf

**Comment by Nithyavasudevan** [comment]
seems to work for other data
