### ISSUE TITLE
[1] Organisation description not passed to the platform

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#122]
Created an organisation with a description. However, this description seems to be passed as null to the platform as the platform seems to be storing null in the db. This functionality works fine from the test tool for platform.

**Comment by Nithyavasudevan** [comment]
High Sev

**Comment by amercader** [comment]
@Nithyavasudevan @stevenlivz 
To create a new organization you need to send

```
{
    "Name": "Test org",
    "About": "Longer description",
    ...
}
```

but when getting the metadata of an organization you get:

```
{
    "Title": "Test org",
    "Description": "Longer description",
    ...
}
```

Do you prefer that:
1. We put custom logic in place to support this as it is now on the API
2. The CTP supports the field consistently (ie Title and Description both for create/update and read) and we wait for this (current code should work as expected)

Option 1 is easy enough for us, but I'd vote to keep the API consistent.

**Comment by stevenlivz** [comment]
Let us chat with Microsoft tomorrow and see if they can fix this to be consistent.

-----Original Message-----

**Comment by Nithyavasudevan** [comment]
passed now
