### ISSUE TITLE
[2] Organisation metadata update screen does not fetch descritpion

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#123]
When trying to update metadata for an organisation, it doesn't fetch the description from the platform. The api does send this value in the json. i tested using test tool.

![image](https://cloud.githubusercontent.com/assets/7315913/3998474/187c7f9e-2948-11e4-8a03-19a3d43c6518.png)

**Comment by Nithyavasudevan** [comment]
Sev High

**Comment by amercader** [comment]
If the Organization has description, it is fetched, see eg https://ckanfrontend.cloudapp.net/organization/test-org-about

The problem is that the description is not added in the first place because of the issue described in https://github.com/okfn/ckanext-glasgow/issues/122#issuecomment-53742860

**Comment by Nithyavasudevan** [comment]
fetches description back. works fine.
