### ISSUE TITLE
[4] Manage button in organisation page does not fetch current values from platform

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#125]
Created organisation called 'ckan description test'
set the dataset require approval to false.
the db now shows this value.
however when i click manage button to edit this, this field is set to true.
![image](https://cloud.githubusercontent.com/assets/7315913/3999524/0ef1dd08-2951-11e4-8a8d-dd915adbbb48.png)

**Comment by Nithyavasudevan** [comment]
4

**Comment by amercader** [comment]
@joetsoi This is still happening for me

Editing this org, setting "Needs Approval" to false:

https://ckanfrontend.cloudapp.net/organization/edit/org-uat-9-9

When the changes are applied in CKAN, the field stills shows as True in the form.

**Comment by joetsoi** [comment]
I removed the boolean_validator from needs_approval from group_show earlier, I've replaced it and it's now ok

**Comment by Nithyavasudevan** [comment]
Can't really check. Submitting a change to org metadata seems to give a 404. logged in as org admin.

![image](https://cloud.githubusercontent.com/assets/7315913/4217912/c742cae8-38ec-11e4-8ffe-99e7ce4fa2d9.png)

![image](https://cloud.githubusercontent.com/assets/7315913/4217916/d492827e-38ec-11e4-8db2-e0294bef6f19.png)

**Comment by joetsoi** [comment]
fixed auth error in action function

**Comment by Nithyavasudevan** [comment]
works
