### ISSUE TITLE
Groups tab in dataset page

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#128]
The dataset page has a Group tab which seems to have nothing. We do not have the concept of groups yet. Can this be removed please?

![image](https://cloud.githubusercontent.com/assets/7315913/3999790/9847e780-2953-11e4-98f5-cb44f439955f.png)

**Comment by mcginns** [comment]
Group functionality will be fully enabled once the Glasgow theme is implemented. Closing this one.
