### ISSUE TITLE
As a platform administrator, I want to prime CKAN with a knowledge of the organizations that will be using the (integrated) platform so datasets can be allocated to the right place and users are set-up properly

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#13]
As a platform administrator, I want to prime CKAN with a knowledge of the organizations that will be using the (integrated) platform so datasets can be allocated to the right place and users are set-up properly.

I will be supplied with a consistently structured file, complete with organization name, organization ID, relevant usernames, relevant supplementary data about the users, so I can programatically (through the CKAN API), prime CKAN with a knowledge of these organizations and these users.

All users under the organization will be granted organization admin rights until the MS Backend supports more permissions.
## External Dependencies
- [ ] Organization ID being available
- [ ] EC being available
- [ ] File being provided
## Accept Criteria
- [ ] CKAN and the EC Backend have the same organization names and organization IDs, and associated users.

**Comment by Nithyavasudevan** [comment]
We have seen this work many times. Can we close this?
