### ISSUE TITLE
[3] Needs Approval flag not displaying in Dataset Metadata page

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#131]
On the dataset metadata page, the needs approval flag shows as null. The value in the db is 0.

![image](https://cloud.githubusercontent.com/assets/7315913/4000330/942a57b4-2958-11e4-834a-6648daa5018a.png)

**Comment by Nithyavasudevan** [comment]
5

**Comment by adamamyl** [comment]
All datasets on frontend working OK.

**Comment by adamamyl** [comment]
(possibly)

**Comment by Nithyavasudevan** [comment]
checked works
