### ISSUE TITLE
Clicking on a dataset in front screen takes me to incorrect page

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#136]
Created a dataset with title 'NITHYA'

![image](https://cloud.githubusercontent.com/assets/7315913/4014277/e470eadc-2a1e-11e4-8030-ac0eb710df1e.png)
![image](https://cloud.githubusercontent.com/assets/7315913/4014280/ea5e5704-2a1e-11e4-9545-d5873c36997b.png)
![image](https://cloud.githubusercontent.com/assets/7315913/4014285/f8440058-2a1e-11e4-847d-9107edc86c0c.png)

Created another dataset with the title 'nithya' (which shouldn't have been allowed).
![image](https://cloud.githubusercontent.com/assets/7315913/4014320/73d36880-2a1f-11e4-86cb-2895b1ec0d63.png)

![image](https://cloud.githubusercontent.com/assets/7315913/4014325/7b73c62a-2a1f-11e4-8fe4-a7ce095306fb.png)

Went to the organisation page and saw that the second organisation is not listed there
![image](https://cloud.githubusercontent.com/assets/7315913/4014386/1295ef2e-2a20-11e4-8181-e4926dcb91c5.png)

However, when I click on the one titled 'NITHYA' , it takes me to the audit page for 'nithya'
I basically can't access my dataset now.
![image](https://cloud.githubusercontent.com/assets/7315913/4014717/8ad996cc-2a23-11e4-8d87-3f8e2bb43a4d.png)

**Comment by amercader** [comment]
We'll double check the unique title validators

**Comment by amercader** [comment]
Fixed the validators, this should work as expected now

**Comment by Nithyavasudevan** [comment]
working.
