### ISSUE TITLE
Update dataset fails with error

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#138]
1. Created a dataset Bavyaa in Org Karma Creations
2. Tried to update the dataset by changing description.
3. On submitting, get the following error. This works fine when tested from the test tool.

```
The form contains invalid entries:
Message: The CTPEC API returned an error code: 500 : {"Message":"An error has occurred.","ExceptionMessage":"An item with the same key has already been added.","ExceptionType":"System.ArgumentException","StackTrace":" at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n at GCC.CTPEC.Services.DataCollectionService.Controllers.DataSetsController.<UpdateDataSetToOrganisation>d__11.MoveNext() in c:\\B\\1\\15\\src\\Main\\Source\\Services\\GCC.CTPEC.Services.DataCollectionService\\Controllers\\DataSetsController.cs:line 336\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__0.MoveNext()"}
```

![image](https://cloud.githubusercontent.com/assets/7315913/4017373/69cba094-2a3f-11e4-84c3-0787ac0521b8.png)

**Comment by amercader** [comment]
This was caused by the created datasets having the "CreatedBy" extra field added. This is now fixed, so new datasets should be able to be edited correctly. Any existing dataset with the "CreatedBy" custom field will fail.

**Comment by Nithyavasudevan** [comment]
@amercader - The platform are going to remove CreatedBy field as a custom metadata. I am guessing this fix won't impact that?

**Comment by Nithyavasudevan** [comment]
@amercader - The Createdby field seems to have been suppressed in the front screen?

**Comment by adamamyl** [comment]
Being removed in CTPEC.

**Comment by Nithyavasudevan** [comment]
Fix to be reverted

**Comment by Nithyavasudevan** [comment]
To be tested after Platform delivers fix

**Comment by amercader** [comment]
@Nithyavasudevan we need the "Resolved" label to keep track of the issues that have been fixed on the code base (ie that they are done on our side and that we can move to the next one)
I've renamed them to "OK Resolved" and changed the colour, so please let us handle this one and don't remove it from issues.
I suggest that when you are happy that an issue has been resolved you just close it
Thanks!

**Comment by Nithyavasudevan** [comment]
I will not look at resolved then. Unless something says Ready for Testing I will not look at it. MAkes it easier that way.

**Comment by amercader** [comment]
Great

**Comment by Nithyavasudevan** [comment]
code not yet reverted.. I will remove ready for testing.

**Comment by amercader** [comment]
As of now, the platform API is still returning the [CreatedBy](https://gccctpecmetadataservicesint.cloudapp.net/Metadata/Organisation/a5ee39a1-7392-446e-a2c5-b3db9d141233/Dataset/e91759eb-9a77-4379-8022-287953ea861a/File/599de55e-d295-4eea-9f69-1d6912abd5dd) field that was the original cause for this failure. If we remove the code to handle this field, the issue will come up again, affecting your testing and we will need to look into it again

We can revert it (although it's completely unnecessary) when the issue is fixed on the platform API.

**Comment by Nithyavasudevan** [comment]
yep.. am hoping to get the fix for this on Mnday. Will update you.

**Comment by adamamyl** [comment]
MS have now deployed (hopefully) a fix -- to UAT environment

**Comment by adamamyl** [comment]
Try after #157 is closed

**Comment by Nithyavasudevan** [comment]
Works fine
