### ISSUE TITLE
As an authenticated user, I need to be able to create datasets so that I can add datasets to CKAN

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#14]
As a CKAN developer, I need to alter CKAN so it supports the EC processes to create datasets, metadata, and files.
## Notes

The preferred approach for this user story is an asynchronous process, something like
- Create dataset and metadata in one step via CKAN forms
- Call back to the EC APIs (dataset, metadata)
- Update the user through their browser

Users can create datasets and associated metadata via CKAN, which are then pushed via API calls to the EC.

Dataset titles should be **unique for each organization** to avoid EC imposed limitations, which will cause a failure when pushed to the API (if the API behaves as spec'd).

On data upload send a POST request to a API, and respond to HTTP Status code
## External dependencies

EC APIs (and their endpoints and schemas) for:
- [ ] Metadata
- [ ] Dataset
## Accept Criteria
- [ ] A user with a valid auth token for EC, will be able to create datasets in CKAN, using the (modified) system to upload their dataset. 
- [ ] A request with an invalid authentication token should result in an Access Denied error message in CKAN.

**Comment by adamamyl** [comment]
This includes creating a custom dataset schema with the validators needed and the templates

**Comment by adamamyl** [comment]
See #34 for files. (split out)

**Comment by nickstenning** [comment]
Signed off.
