### ISSUE TITLE
User created on platform not harvested in CKAN

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#140]
Created an organisation on the platform using the test tool. Required audit generated successfully.
However, even after a long time, the organisation is not harvested in CKAN. 

Organisation name : Valhalla
Org ID : ba9214b4-ea8b-4fc7-afdf-6cb09e79506f

**Comment by adamamyl** [comment]
Do things created in the test tool generate a changelog entry?

**Comment by Nithyavasudevan** [comment]
yes

Date: Mon, 25 Aug 2014 06:57:24 -0700

**Comment by amercader** [comment]
The harvesting had stalled due to a bug in the changelog harvester. This is now fixed and the pending changes have been applied, eg:

https://ckanfrontend.cloudapp.net/organization/valhalla

**Comment by Nithyavasudevan** [comment]
Harvesting still seems to have issue. Users are not getting fully harvested. User Superstar@GCCCTPECADINT.onmicrosoft.com not found on CKAN.

**Comment by joetsoi** [comment]
@adamamyl, @Nithyavasudevan , this is the issue yesterday where items in the change log do not give the full username back
This is the user , notice the name has @GCCTPE...

```
{

    "UserName": "Superstar@GCCCTPECADINT.onmicrosoft.com",
    "About": "This is superstar",
    "DisplayName": "Rajini",
    "Roles": [
        "SuperAdmin"
    ],
    "FirstName": "Super",
    "LastName": "Star",
    "UserId": "edf0cdf8-44bf-4bbc-be45-054f8fa0ec4b",
    "IsRegistered": false,
    "OrganisationId": null,
    "Email": "wej@j.l"

},
```

yet in the createuser log changelog the user is just superstar.

```
{

    "Timestamp": "2014-08-25T12:50:29.575101Z",
    "Component": "DataPublication",
    "OperationState": "Succeeded",
    "AuditId": "0635445678294627876",
    "Command": "CreateUser",
    "RequestId": "c61e6edf-9e3b-461b-b535-6a8f2a04603c",
    "CustomProperties": {
        "UserName": "Superstar",
        "OrganisationId": ""
    },
    "Owner": "SuperAdmin1@GCCCTPECADINT.onmicrosoft.com",
    "AuditType": "UserCreated",
    "Message": "User 'Superstar' was created.",
    "ObjectType": "User"

},
```

so if we get the wrong user name, we can't harvest in the user.

**Comment by adamamyl** [comment]
Action needed to include fully-qualified username in ChangeLog.

**Comment by Nithyavasudevan** [comment]
Added defect on MSFT - 4249

**Comment by adamamyl** [comment]
Try after #157 has been closed.

**Comment by joetsoi** [comment]
this looks fixed in on the microsoft end to me now

```
{

    "Timestamp": "2014-09-09T13:24:48.5078096Z",
    "Component": "DataPublication",
    "OperationState": "Succeeded",
    "AuditId": "0635458658886362019",
    "Command": "CreateUser",
    "RequestId": "2e95a5d4-a3d3-4655-b44b-2038d9af24e0",
    "CustomProperties": {
        "UserName": "mario@GCCCTPECADUat.onmicrosoft.com",
        "OrganisationId": ""
    },
    "Owner": "869af136-7263-4336-980e-8929b6cc9070",
    "AuditType": "UserCreated",
    "Message": "User 'mario@GCCCTPECADUat.onmicrosoft.com' was created.",
    "ObjectType": "User"

}
```

I'll have to check later for user updates

**Comment by Nithyavasudevan** [comment]
cool.. this was fixed in their previous build.
