### ISSUE TITLE
Create link in top navigation for /create_users

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#141]
To the right of the '/ckan-admin' link, create a link/tooltip to /create_users, that's only visible if the user logged in is:
- [ ] A SysAdmin
- [ ] An org-admin

**Comment by amercader** [comment]
Added here:

![qfljft1](https://cloud.githubusercontent.com/assets/200230/4078012/1ed294a2-2ec8-11e4-8a76-54a211eb90fe.png)

**Comment by Nithyavasudevan** [comment]
CAnnot see link
![image](https://cloud.githubusercontent.com/assets/7315913/4088414/cdb6f49c-2f5c-11e4-86e1-9f755b7e66b6.png)

**Comment by amercader** [comment]
Sorry, wrong label

**Comment by Nithyavasudevan** [comment]
Checked. Link available. Takes me to create user page. Not tested create users yet.
