### ISSUE TITLE
Create new file version submit doesn't submit gracefully

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#145]
After creating a new file version and submitting the request, there is a message on screen with request id. But the page still remains in edit mode on the file version page. This looks very clumsy.

![image](https://cloud.githubusercontent.com/assets/7315913/4100254/00206466-308b-11e4-99f7-328c88bc4a26.png)

**Comment by adamamyl** [comment]
Outcome of the action should be similar to submit dataset/file:

passed to platform with this status ID

**Comment by Nithyavasudevan** [comment]
checked. works fine.
