### ISSUE TITLE
External url should open a new page

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#146]
When I am on a file page and click on Go To Resource link, when the link is an external url, it should open the url in a new page and not open the link on the same page.

![image](https://cloud.githubusercontent.com/assets/7315913/4100246/8117b2b4-308a-11e4-8550-e2347b82d20e.png)

**Comment by adamamyl** [comment]
Not according to the [W3C](http://www.w3.org/TR/WCAG20-TECHS/G200.html):

> In general, it is better not to open new windows and tabs since they can be disorienting for people, especially people who have difficulty perceiving visual content.

**Comment by adamamyl** [comment]
Ultimately, it is entirely the **user's** choice over how/where links should open.

**Comment by mcginns** [comment]
Closing this one. User has the option to open in a new window if they like.
