### ISSUE TITLE
Adding file version doesn't create a pending resource link until approved

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#147]
After adding a file version, there is no redirection to display audits. If I go over to the files page, it doesn't display anywhere that a file version is pending approval.

![image](https://cloud.githubusercontent.com/assets/7315913/4102167/ffae15d6-311c-11e4-8702-80fff049cbce.png)

![image](https://cloud.githubusercontent.com/assets/7315913/4102169/0bb64d94-311d-11e4-9378-31b6f57329a5.png)

The file just appears after harvest

![image](https://cloud.githubusercontent.com/assets/7315913/4102174/6c8c73dc-311d-11e4-917b-a8fb0952c4d1.png)

**Comment by adamamyl** [comment]
Tie in with #145

**Comment by Nithyavasudevan** [comment]
tested. works ok.
