### ISSUE TITLE
As a CKAN developer, I need to extend CKAN's backend to enable EC interoperability to store IDs for adding/metadata/datasets/files

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#15]
As a CKAN developer, I need to extend CKAN's backend to enable EC interoperability to store IDs for adding/metadata/datasets/files.

I will add temporary tables to map the IDs provided, so the status can be followed for a given operation. This will include the CKAN Task ID, and the EC GUID, and possibly other information such as the status code received by which API from the EC.
## External dependencies

Schema etc from MS (from MS userstory 10)
## Acceptance criteria
- [ ] That there is a mapping of CKAN Task IDs and EC GUIDs, and that these can be tracked;
- [ ] Ultimately, that ingestion works.
## Parent User Story
#14

**Comment by adamamyl** [comment]
The **Data Collection API** for **dataset creation** will have this signature:

`POST https://<HostURL>/Datasets`
`<JSON body defining content>`

All characters in Metadata properties are stored in UTF-8 format

The mandatory metadata is supplied in JSON format:
-  Title (255 chars, unique within an org, mutable)
-  Description (4000 chars, mutable)
-  Maintainer Name (255 chars)
-  Maintainer Contact (string normally contains UserId/email 255 chars) There is no validation of this string.
-  License  (string 255 chars)
-  Openness Rating (Integer value 0-5)
-  Quality (Integer value 0-5)

The optional metadata is is supplied in JSON format:
-  Tags: string - comma separated list (optional, max 64000 chars total)
-  Published on behalf of: string (optional, max 255 chars)
-  Usage Guidance: string (optional, max 255 chars) 
-  Category: string (optional, max 255 chars)
-  Theme: string (optional, max 255 chars)
-  Standard Rating: integer (optional, range 0-5)
-  Standard Name: string (optional, max 255 chars)
-  Standard Version: string (optional, max 255 chars)

## Scenarios

### Successful submission

Given I'm authenticated and the request is well formed,
When I send dataset creation request,

Then:
- the Dataset will be associated with the Organisation which the user defined by the OAuth token the user belongs to
- I receive a unique request ID as JSON in the HTTP response with an HTTP Status of 200

### Bad request

Given I'm authenticated and I send a malformed\* dataset creation request
Then I receive an HTTP status of 40x and a JSON response containing the error details
- A Malformed request could be:
- Invalid JSON
- Mandatory fields missing
- Type of property field is incorrect
- Length of properties exceeds max limit

### Server error

Given I'm authenticated, I send a dataset creation request and an error occurs during internal processing
Then I receive an HTTP status of 500 and a JSON response containing the exception details

### Invalid credentials

Given I supply an invalid OAuth token with the dataset creation request I submit
Then I get a an HTTP 40x level status response back. There will not be any JSON response.

**Comment by adamamyl** [comment]
The Data Collection API for **file creation** will have this signature:

`POST https://<HostURL>/Files`
`<JSON body defining metadata and file content>`

The mandatory metadata is supplied in JSON format:
-  Title: string(required, max 255 chars)
-  Filename: string (max 255 chars) Must conform to standard file name conventions and is url encoded and is not case sensitive
-  Description: string (required, max 64000 chars)
-  Type: string (required, max 255 chars - MIMEType not validated)
-  Dataset ID: (required, string in guid format will be manually supplied)

The optional metadata is supplied in JSON format:
-  Creation date: date and time in UTC-0 timezone format: YYYY-MM-ddThh:mm:ss
-  License: string (optional, max 255 chars)
-  Openness Rating: integer (optional, range 0-5)
-  Quality: integer (optional, range 0-5)
-  Standard Rating: integer (optional, range 0-5)
-  Standard Name: string (optional, max 255 chars)
-  Standard Version: string (optional, max 255 chars)

## Scenarios

### Successful submission

Given I'm authenticated and the request is well formed,
When I send a file ingestion request,

Then:
- the file is associated with the Organisation which the user defined by the OAuth token belongs to
- I receive a unique request ID as JSON in the HTTP response with an HTTP Status of 200

### Bad request

Given I'm authenticated and I send a malformed\* file creation request
Then I receive an HTTP status of 40x and a JSON response containing the error details
- A Malformed request could be:
  -  Invalid JSON
  -  Mandatory fields missing
  -  Type of property field is incorrect
  -  Length of properties exceeds max limit

### Server error

Given I'm authenticated, I send a file creation request and an error occurs during internal processing
Then I receive an HTTP status of 500 and a JSON response containing the exception details

### Invalid credentials

Given I supply an invalid OAuth token with the file creation request I submit
Then I get a an HTTP 40x level status response back. There will not be any JSON response.

## Remarks

No versioning for iteration 1

**Comment by adamamyl** [comment]
Creation of content from CKAN API (not front-end). API impact. Ajax call-back/poll for status/correlation id.

Temporary table for CKAN ID and EC Status, with dataset name, e.g., if user x creates "Carparks" and user y creates "Carparks" we throw an exception/error message to user.

First validation on CKAN (file uniqueness, missing mandatory metadata).

**Comment by amercader** [comment]
This is now done. Request Ids (and other relevant data for each request) is stored internally in the TaskStatus table, and the relevant functions to query it are in place.
