### ISSUE TITLE
Unable to create a dataset with name "new"

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#159]
When I create a dataset with Title "New", it gives me an error saying Name: That name cannot be used. This seems to be a new validation on the front end. I vaguely remember this was working earlier. The platform has no such restrictions. So there could be a situation in future where another source has created a dataset on the platform called "new" and CKAN cannot be used to edit that dataset.

![image](https://cloud.githubusercontent.com/assets/7315913/4186585/6e5997da-3762-11e4-9f61-3c4c92e58864.png)

**Comment by mcginns** [comment]
This relates to defect 156 and use of reserved words for user created datasets, resources and custom metadata.
