### ISSUE TITLE
As a CKAN developer, I need to extend CKAN's backend to enable EC interoperability to send data to the EC platform

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#16]
As a CKAN developer, I need to extend CKAN's backend to enable EC interoperability to send data to the EC platform.

Having understood the workflow (#14), and with temporary tables (#15) to aid the process, I need to build the functionality to handle the data transmission within CKAN's API.
## External Dependencies
- [ ] EC Schemas/End points
## Accept Criteria
- [x] Via the API, I can transfer files, metadata, and datasets to the EC API
- [x] An EC authenticated user with appropriate permissions for the organization in question, will be able to upload files in CKAN, using the (modified) system to upload their files.
- [x] The file should be passed to the EC file ingestion system, with status codes from that forming status messages in CKAN.
- [x] The file(s) should be viewable through CKAN, complete with EC filestore URI.
## Parent User Story
#14

**Comment by adamamyl** [comment]
Need clarification from MS on how file is uploaded  "Temporary storage of the file (by CKAN) in a sandbox?"

Size limit <2GB

**Comment by adamamyl** [comment]
Public URI for file will be returned by EC (to be consumed by CKAN).

**Comment by amercader** [comment]
The functionality for sending files to the EC API is now in place.
