### ISSUE TITLE
Cannot find out status of user creation request

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#160]
On creating a new user, there is no link/location on the front end for me to actually check the status of the user creation. User creation is now a 2 step process (except for members) and I need to know status of step 1 before i go and keep trying to see if i can perform step 2.

**Comment by Nithyavasudevan** [comment]
Looked at Pending user screen. It doesn't seem to list the requests.
Case in Point Request ID 2e95a5d4-a3d3-4655-b44b-2038d9af24e0

![image](https://cloud.githubusercontent.com/assets/7315913/4202081/3e646956-3825-11e4-8328-50c35e9d6035.png)

screenshot of changelog from test tool
![image](https://cloud.githubusercontent.com/assets/7315913/4202101/555615c4-3825-11e4-92d3-7c7cdf4c779c.png)

**Comment by Nithyavasudevan** [comment]
Agreed with Joe that there is no success audit displayed. If user request not in pending user screen, that means it is created. However, the status message for a failed request doesn't display either. Request ID 5128383a-3ebc-485b-b950-6f2339c25ce2

![image](https://cloud.githubusercontent.com/assets/7315913/4202241/6931777c-3826-11e4-9ee9-3c906b63dd7c.png)

![image](https://cloud.githubusercontent.com/assets/7315913/4202247/747fbf44-3826-11e4-940a-24254497f7db.png)

**Comment by joetsoi** [comment]
I've changed the pending users page to be clearer and contain some more useful information such as the user name and the last time the task was checked. Clicking on the refresh button will take you to the task status page and update the ckan task to say it has errored.

![pending_users](https://cloud.githubusercontent.com/assets/241130/4232020/f5796740-3997-11e4-9de9-78d870e2d02b.png)

**Comment by Nithyavasudevan** [comment]
Doesn't work for Org Admin
![image](https://cloud.githubusercontent.com/assets/7315913/4232546/5468a026-399e-11e4-9a61-4819a4e1c1ea.png)

**Comment by mcginns** [comment]
Works fine for Org Admin now

![image](https://cloud.githubusercontent.com/assets/7511445/4270879/433cf000-3cd1-11e4-9cc9-658ca042d3f1.png)

Ok to close
