### ISSUE TITLE
Pending changes tab to be hidden

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#161]
When logged in as a member user (harrypotter@gccctpecaduat.onmicrosoft.com), the "Pending Changes" tab in organisations and datasets should not be visible. Instead it is visible and gives an auth error when accessed for datasets alone.

![image](https://cloud.githubusercontent.com/assets/7315913/4188171/23971ee4-3770-11e4-8777-92d05e9488a8.png)

![image](https://cloud.githubusercontent.com/assets/7315913/4188179/36a76d5e-3770-11e4-8b3f-aee7ca639b6b.png)

**Comment by adamamyl** [comment]
(helpers in Glasgow extension should ease this)

**Comment by mcginns** [comment]
Pending Changes tab is still visible to member users on both Organisations and Datasets. How easy is it to hide the tab based on role?

**Comment by mcginns** [comment]
Re-tested and passed. Logged in as member user - pending changes tab is not visible for Datasets and Orgs

![image](https://cloud.githubusercontent.com/assets/7511445/4402603/2e442022-4499-11e4-9187-529d5e4b6346.png)
