### ISSUE TITLE
Able to add registered user to an organisation

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#162]
When trying to add a user to an organisation, i should not be given an option to add a registered user. However, CKAN lets me submit such a request to the platform. The platform however rejects this.

![image](https://cloud.githubusercontent.com/assets/7315913/4188322/698cecc0-3771-11e4-86a3-b747cec91f71.png)

**Comment by adamamyl** [comment]
By "registered user" do you mean "CKAN user" (i.e. a user account that is not a CTPEC/WAAD user)?

**Comment by Nithyavasudevan** [comment]
With new requirements for CKAN, we have now made "Registered Users"="CKAN Users". However, the platform can still have registered users which are non WAAD users. So when CKAN does a harvest, it harvests all users back including users with no domain (platform non waad registered users)
