### ISSUE TITLE
Unable to move a platform user from an organisation back to a member

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#163]
When logged in as an OrgAdmin and trying to remove a platform user from an Organisation back to being a member user, CKAN gives an error

![image](https://cloud.githubusercontent.com/assets/7315913/4188480/fc50bc0c-3772-11e4-995b-0eb9f6d0c886.png)

Once this error appears, i need to refresh the screen to get back the roles.

![image](https://cloud.githubusercontent.com/assets/7315913/4188517/627ee198-3773-11e4-8fa3-4611ad283810.png)

**Comment by adamamyl** [comment]
Red X....

**Comment by Nithyavasudevan** [comment]
Red X causes internal server error
