### ISSUE TITLE
Member option to be removed from roles list when adding a user to an organisation

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#164]
When adding a user to an organisation, "Member" should not be present in the drop down box as member cannot belong to an organisation. On selecting it, the values in roles list vanish

![image](https://cloud.githubusercontent.com/assets/7315913/4188645/a08bf402-3774-11e4-96d2-9569872950ff.png)

**Comment by adamamyl** [comment]
The "Members" rôle **should** exist so that users can follow an organization to get updates and interact with the dataset.

This has been part of the design and is one of the reasons why a citizen (etc) may want to register on CKAN.

**Comment by Nithyavasudevan** [comment]
Member role should exist in the system. But not in that dropdown or hidden there. As selecting it there just kills the system.That isn't right design as MEmber is never a member of an organisation.

**Comment by mcginns** [comment]
Has this one been scheduled for fix yet?

**Comment by adamamyl** [comment]
Only affects CKAN users &#8212; **no** impact on platform users.
