### ISSUE TITLE
Delete file version doesn't let me check request status

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#173]
Logged in as OrgEditor, when I delete a specific file version, there is a message on screen saying request submitted, but there is no place for me to see the request status

![image](https://cloud.githubusercontent.com/assets/7315913/4216330/7b6490b6-38d8-11e4-8fdd-535bb4adc20c.png)

**Comment by Nithyavasudevan** [comment]
still seems same.. as editor
![image](https://cloud.githubusercontent.com/assets/7315913/4234872/05b75bd0-39bb-11e4-8f2e-54e26ac62a66.png)

**Comment by amercader** [comment]
The status is shown on the dataset page, under "Pending Operations on Resources"
It kind of breaks the user flow to redirect to that page, but we can do it if you think that makes more sense.

![woxwfek](https://cloud.githubusercontent.com/assets/200230/4235316/7911597a-39be-11e4-9d41-95d475f79891.png)

**Comment by Nithyavasudevan** [comment]
Nope. As long as its there, it should be ok..

**Comment by Nithyavasudevan** [comment]
The delete file version status request doesn't actually show the title of the version being deleted. instead it shows the latest version

**Comment by mcginns** [comment]
Adam, I'm ok to close this (on the basis we can see the pending status now) as long as we make #181 a P2-candidate.

**Comment by adamamyl** [comment]
#181 P2'd.
