### ISSUE TITLE
Show title of deleted version

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#181]
À propos to #173, there is slight defect in that we don't show the title of a deleted version but of
the most recent one (although the status is shown).

**Comment by Nithyavasudevan** [comment]
Yes.. Just causes a bit of panic when you think you have deleted the wrong version.. 😊

Sent from my Windows Phone

**Comment by mcginns** [comment]
Deleted resource version "Version Check" below:

![image](https://cloud.githubusercontent.com/assets/7511445/4402306/97b94f12-4496-11e4-9a4b-288660f20c25.png)

The pending operation still shows the title of the latest version and now an additional GUID. This doesn't clarify the situation for the user or improve the user experience. 

![image](https://cloud.githubusercontent.com/assets/7511445/4402323/c09190e8-4496-11e4-97ba-f470d7f5dcff.png)

The updated functionality should present the title of the file version being deleted to avoid confusion.

**Comment by joetsoi** [comment]
I've now changed this to the title

**Comment by mcginns** [comment]
Looks good Joe. Re-tested - happy to close.
