### ISSUE TITLE
As a CKAN Tester, I need to build a stub to facilitate testing

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#19]
To enable me to test the functionality our team builds, we need to develop a lightweight stub for testing purposes that delivers the responses that the EC would, under all defined circumstances.

This should return/store the actions and outcomes of the operation.

This needs to act in the same way that the EC built objects would.
## Acceptance criteria

Should have a user interface to inspect message output.
## Related items

[Specification of MS APIs](https://docs.google.com/a/okfn.org/spreadsheets/d/1QjlOdpgroV0Yzj9c7gcVNUbYndJVw_9RBun4nhHg9yE/edit#gid=1827328942)

**Comment by adamamyl** [comment]
Need collaboration with Microsoft on actualities. See Yammer.

**Comment by amercader** [comment]
Started work on this as I needed it for my tests, see 

https://github.com/okfn/ckanext-glasgow/blob/master/ckanext/glasgow/tests/mock_ec.py
