### ISSUE TITLE
As a CKAN Systems Administrator I need to build a deployment system to enable a fast, predictable, scalable deployment of the CKAN components

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#20]
As a CKAN Systems Administrator, I need to build a "playbook" or similar to have a largely automated / one command installation of the CKAN product and appropriate extensions, including those built under this project.

I need to be able to deploy development versions to sandboxes, a signed-off branch to an integration environment, and a further signed-off copy to production.

I need to have repositories in appropriate states to facilitate this behaviour, unless @nickstenning says otherwise.
## Dependencies
- [x] Provision of Windows Azure Instances to the [OKF provided spec](https://docs.google.com/a/okfn.org/spreadsheets/d/1VwQ7UnUTmkHlDPb2xgtz1yMx_ZdD16C8p6Ik9Xu6BNc/edit#gid=0)
- [x] Public IP addresses without NAT
- [x] Root access
- [x] Minimal installation of Ubuntu 12.04 LTS (Server edition)
- [x] Branches in repositories
## Acceptance criteria
- [x] Sight of the deployment script
- [x] CKAN deployed via this script
- [ ] Instructions on how to deploy, assuming a basic Linux knowledge

**Comment by nickstenning** [comment]
Closing #20. Remaining work in #81 in new iteration.
