### ISSUE TITLE
As a data consumer, I want to be able to find data, metadata, files, resources that aren't indigenous to CKAN

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#23]
Additional data, metadata, files will be created outside of CKAN, but stored in the EC. 

As a data consumer, I don't care about this, I just want data. Available to me through CKAN.

CKAN should periodically harvest a defined endpoint (and iterate through ids for organization & datasets), and pull in to the CKAN catalog these metadata so those externally created resources appear within CKAN.
## Dependencies
- APIs and Endpoints from the EC
- Support for listing/searching
## Accept criteria
- [ ] Once content is created, and subsequently edited, CKAN should be made aware of these changes.
- [ ] Changes made external to CKAN will be visible within CKAN after the next refresh window, or through an alternative -- non harvested (i.e. the service bus, if implemented) -- method.

**Comment by adamamyl** [comment]
New datasets (building applications) are created in CKAN. The ID is used by 'adaptors' that publish data.

The file API would be used to add content externally to CKAN.

Flag in CKAN for immutable datasets (ones created in CKAN)

[ACTION] EC created content will be assumed that it has been validated, externally -- check EC validation rules (lengths, regex, etc) are consistent with CKAN. CKAN will check for very basics, though.

Validation schema to be written (for push), harvest stuff written at same time.

**Comment by Nithyavasudevan** [comment]
Doesn't this already work now anyway using the harvester? Can we close this?
