### ISSUE TITLE
Provision Azure machines

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#24]
https://manage.windowsazure.com (creds in lastpass)

Machines to provision are
- [x] okfsandboxdb
- [x] okfstandboxfe // frontend
- [x] okfstagingdb1
- [x] okfstagingfe

Related: #20

**Comment by adamamyl** [comment]
(details in "Glasgow Azure SSH" lastpass)

**Comment by adamamyl** [comment]
For initial extensions let's go with 
- [ ] ckanext-googleanalytics
- [ ] ckanext-qa
- [ ] ckanext-spatial
- [ ] ckanext-harvest

**Comment by adamamyl** [comment]
Wondering about ckanext-realtime, but probably good to have a discussion about that.

**Comment by amercader** [comment]
I'm not sure ckanext-realtime is ready for production and besides we still need to work on data on future iterations.

**Comment by adamamyl** [comment]
let's park ckanext-realtime (for now): but keep an eye on it
