### ISSUE TITLE
As a site visitor I want to be able to list all datasets in an organisation so I can see the datasets the organisation published

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#27]
## Background Info

API

The Metadata API for listing datasets in an organisation will have this signature:

``` html
GET https://<HostURL>/Organisations/<OrganisationID>/Datasets?<paging and sort parameters>
```

``` html
<paging and sort parameters>
```

are:
- $top - the size of page to return. 
  If parameter is omitted, the default value is 100. 

Minimum page size is 1 and maximum page size is 100. If the user specifies value outside this range, it is treated as if they've entered the default value (100).
- $skip - the number of top items to skip in the results. 

If parameter is omitted, the default value is 0.

Minimum value is 0, maximum value is: number datasets in organisation. If the user specifies value lower than minimum value (0), it is treated as if they've entered the minimum value. If the user specifies value higher than maximum value, he/she should get an empty list.
- $orderby - the name of parameter to sort by.
  Valid values: title (sort ascending by title, case insensitive), created (sort ascending by date and time the organisation was created on the platform)

If parameter is omitted, the default value is "created".

If the user specifies value outside the valid range, it is treated as if they've entered the default value ("created").

The response will contain a page of a list of all datasets in specified organisation available on the platform. Each dataset will have all its metadata listed (including ID and title).

Response will be JSON encoded.
## Accept Criteria
-  [ ] Given that I view the organizations page, on clicking 'datasets', I see a listing of datasets and their metadata
-  [ ] Given that I have tried to view the datasets of a non existing organisation, I receive a response with HTTP 404 (Not Found) status code and an explanation that the organisation does not exist.

**Comment by adamamyl** [comment]
(depends on: #26 )

**Comment by Nithyavasudevan** [comment]
What is the default sorting within CKAN? Is it configurable within the configuration set? Also what is the paging size?
