### ISSUE TITLE
As a site visitor I want to be able to list all files in a dataset (latest version) so I can see all files in a dataset

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#29]
## Background Info

API
There is an HTTPS REST API for listing files in a dataset with the following signature:

``` html
GET https://<HostURL>/Metadata/Organisation/<organisationId>/Dataset/<datasetId>/File{/<FileId>}
```

Response is JSON formatted and contains a list of file records containing the metadata for each file in the dataset including `<FileId>` which is needed for downloading the file.

Only the latest version of each file will be returned.

The returned data will include the fileId and the full external URL for downloading the file.

If the optional `<filename>` is specified then only the metadata for that file is returned.
#### Success

Given specified `<organisationId>` and `<datasetId>` exist (and dataset belongs to specified organisation)

When the user requests all the files in dataset

Then the user receives a list of file records containing the metadata for each file with an HTTP 200 response
#### Failure

Given specified `<organisationId>` and `<datasetId>` do not exist (or dataset does not belong to specified organisation)

When the user requests all the files in dataset

Then the user receives HTTP 404 response.
## Accept Criteria
- [ ] The latest versions of all files within the dataset should be displayed;
- [ ] If there are no files within the dataset, then nothing further is displayed.

**Comment by adamamyl** [comment]
Accept criteria dependent on #34

**Comment by nickstenning** [comment]
Pending signoff by @Nithyavasudevan, this can be closed.

**Comment by Nithyavasudevan** [comment]
Able to see files in the dataset. Since versioning hasn't yet been delivered, can't check that it does display the latest version. But happy to test that with I3 user stories.
