### ISSUE TITLE
As a site visitor I want to be able to download the latest version of an existing file within a dataset so I can view the file.

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#30]
## Background Docs

API
The public API for data consumption services will follow this signature:

``` html
http://<Hosturl>/Download/Organisation/<organisationId>/Dataset/<dataSetId>/File/<FileId>
```
## Implementation discussion points
- Pulled from file API
- Potential issues around TTLs on file API?
- Notice the HTTP Status Codes.
- Harvesting sync thoughts.
## Accept criteria
- [x] The latest version of the file within the dataset should be downloadable. It should have the original name that it was uploaded with.

(diagram of UI mock-up to be added)

**Comment by joetsoi** [comment]
I've added some screenshots as the versions api doesn't seem to be working on the platform. I took these by mocking the platform api

There's a additional action when clicking on the 'Explore' resource button
![pkg_show_list](https://cloud.githubusercontent.com/assets/241130/3437236/871ca39e-00ac-11e4-82df-cf6b0fd01648.png)
Which will take you to this page listing the revisions down the side of the page and the metadata for the latest revision. There is also a download link, this is reliant on the platform having a FileExternalUrl in it's payload.
![version0](https://cloud.githubusercontent.com/assets/241130/3437240/8de66ce6-00ac-11e4-86b9-22f9fff9bac5.png)
you can check the metadata for other revisions by clicking on the sidebar which will highlight the selected revision.
![version1](https://cloud.githubusercontent.com/assets/241130/3437242/9230e48e-00ac-11e4-827e-30b45117393d.png)

**Comment by Nithyavasudevan** [comment]
@joetsoi - Not sure if this helps, but versions api on the platform seems to be working for me. I tested it using the api test tool. A search for all files in a dataset seems to fetch the latest versions of files..

**Comment by joetsoi** [comment]
good to know, looks like the docs I was given were wrong. The version ending point is

Metadata/Organisation/<dataset_id>/Dataset/<datasetId>/File/<file_id>/Versions
not
Metadata/Organisation/<dataset_id>/Dataset/<datasetId>/File/<file_id>/Version

which was giving me 500 errors, so I thought the endpoint was broken

**Comment by Nithyavasudevan** [comment]
:+1: any more issues, do ping me and i can try and help..

**Comment by nickstenning** [comment]
Demoed today.

**Comment by adamamyl** [comment]
I3 Test Cases: Pass.
