### ISSUE TITLE
As an Organisation Editor/Admin / SysAdmin, I want to be able to initiate creation of a new version of an existing file in a dataset, so that I can create new file versions

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#32]
## Technical consideration
- Enhancement to CKAN Ingestion process, to consider the spec
## Background

API
The Data Collection API for new file version creation will have this signature:

``` html
POST https://<HostURL>/Files/Organisation/<OrganisationId>/Dataset/<DatasetId>{/File/<fileId>}
```

``` html
<JSON body defining metadata and file content>
```

The core metadata (mandatory and optional) is supplied in JSON format:
- File ID: long integer (identifier of an existing file)
- Dataset ID: long integer (reference to Dataset)
- Title: string (required, max 255 chars)
- Filename: string (required, max 255 chars) &#8212; Must conform to standard file name conventions and is url encoded and is not case sensitive (Validation regex: `^[^\p{Cc}<>:""\/\\|?*]+$`)
- Description: string (required, max 64K chars)
- Type: string (required, max 255 chars)
- Creation date: date and time in UTC timezone (optional)
- License: string (optional, max 255 chars)
- Openness Rating: integer (optional, range 0-5)
- Quality: integer (optional, range 0-5)
- Standard Rating: integer (optional, range 0-5)
- Standard Name: string (optional, max 255 chars)
- Standard Version: string (optional, max 255 chars)

The operation returns a unique correlation ID.

If the user has specified FileID, this user story takes place. Otherwise, standard file creation occurs as described in user story #77, amended by #268 (virus scan) and #316 (audits).

Comments:
- All files can be versioned.
- All versions of the same file must have the same FileId property, but different Version tags.
- Different version of a file can have the same or different file name.
- File names within dataset (any version) don't have to be unique.
## Accept Criteria
- [ ] Given I have rights to create a file (by organization membership), when I submit a request to create a new version of an existing file, I am able to upload a new file

**Comment by adamamyl** [comment]
Gather thoughts on UI for how to create a new version of the file.

**Comment by adamamyl** [comment]
Pre-populate metadata for new version based on previous item(s).

**Comment by adamamyl** [comment]
Add a new field to facilitate this, possibly a Controller Action (did I capture that properly?)

**Comment by nickstenning** [comment]
After discussion with Stuart and co in Glasgow, my current understanding is that new "versions" are not created automatically when a resource is edited. This should probably be a "create new" version button that is visible only on the "view all versions" page.

To rephrase, this story is about an explicit "create a new version" feature.

**Comment by adamamyl** [comment]
Ready for testing.

**Comment by joetsoi** [comment]
file request updates in 50ce0cb18cfa0f72a49aa7a29881f8f5481135d2

**Comment by Nithyavasudevan** [comment]
works for SUperadmin, org admin and editor
