### ISSUE TITLE
As an site visitor I should be able to download a specific version of a file within a dataset so I can view the file

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#33]
## Technical considerations

Honour the EC API restrictions (see MS User Story 246).

http://[Hosturl]/Download/Organisation/[organisationId]/Dataset/[dataSetId]/File/[FileId]/version/[versionId]
## Accept criteria
- [x] On the list datasets page, under the resources  (#31) view, add/ensure there's a 'download' button.

**Comment by nickstenning** [comment]
Demoed today.

**Comment by adamamyl** [comment]
I3 Test Cases: Pass.
