### ISSUE TITLE
As an authenticated user I should be able to upload files so i can add files to a dataset

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#34]
As a CKAN developer, I need to alter CKAN so it supports the EC processes to create metadata, and files.
## Notes

The preferred approach for this user story is an asynchronous process, something like
- Create dataset and metadata in one step via CKAN forms
- Call back to the EC APIs (dataset, metadata)
- Update the user through their browser
- Upload file(s), appending metadata
  -  but note 10 files will require 10 separate API calls
- Publish the dataset

Users can create datasets and associated metadata via CKAN, which are then pushed via API calls to the EC.

Dataset titles should be **unique for each organization** to avoid EC imposed limitations, which will cause a failure when pushed to the API (if the API behaves as spec'd).

On data upload send a POST request to a API, and respond to HTTP Status code
## External dependencies

EC APIs (and their endpoints and schemas) for:
- [ ] Metadata
- [ ] Files
## Accept Criteria
- [ ] A user with appropriate authentication token for the platform/organisation, will be able to upload files to the appropriate dataset using CKAN, using the (modified) system to upload their dataset. 
- [ ] The file should be passed to the EC injestion system, and should be found in the blob storage

**Comment by nickstenning** [comment]
Complete. Signed off by @Nithyavasudevan.
