### ISSUE TITLE
Keywords/Tags input in the CKAN front end does not seem to be linked to the 'Tags' column in the metadata table on the platform

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#36]
Created a dataset with Title "Integration Test" and CKAN Task ID '85b1fcd8-17ea-43e9-bcfc-16abbfd53b1a' from the CKAN front end. Checked the task_status table and found the record with state = 'sent' and tag_string values of  "nithya,tag,keyword". & "tags": [{"name": "nithya"}, {"name": "tag"}, {"name": "keyword"}]
Dataset was created on the platform with the same title. However, the 'Tags' field seem to be empty. Values from Platform pasted below.

10616   10042   Category    new
10617   10042   Description integration test
10618   10042   License cc-by
10619   10042   MaintainerContact   srinivaslrknler
10620   10042   MaintainerName  Srinivas
10621   10042   OpennessRating  0
10622   10042   PublishedOnBehalfOf C KAN
10623   10042   Quality 0
10624   10042   StandardName    Scottish
10625   10042   StandardRating  2
10626   10042   StandardVersion lkn
10627   10042   Tags  
10629   10042   Theme   popular
10628   10042   Title   Integration Test
10630   10042   UsageGuidance   non

**Comment by amercader** [comment]
@Nithyavasudevan This should be fixed now

**Comment by Nithyavasudevan** [comment]
Retested this and it works fine. DatasetID 11079.
