### ISSUE TITLE
Tags field not permitting all allowed "string" characters

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#38]
Tried to create a dataset with title length of 255 characters and value in the "keyword" field as '%%%££'. On submission of the dataset, an error message appears as follows.

The form contains invalid entries:
•Tag string: Tag "%%%££" must be alphanumeric characters or symbols: -_. 

The specification for the field on the platform is 'Tags: string - comma separated list (optional, max 64000 chars total)'. I am able to create a dataset using these values in the tags field directly on the platform. This front end validation seems to be in contrast with the specification..

**Comment by amercader** [comment]
Fixed, see https://okfsandboxfe.cloudapp.net/dataset/cumque-tenetur-dolores-saepe-harum-omnis-quidem-dolores-20
