### ISSUE TITLE
task_status table does not seem to store dataset details for a dataset creation request when the api responds with a 401

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#40]
Tried to create a dataset with an expired auth token. (CKAN Task id 7968667e-ad52-40cd-9f26-d728571826c3). The api responded with a 401 as expected. On checking the task_status table for the values, the dataset details are not stored in the table. The "state" field has the value "error" but the "error" field is empty. Is this the right behaviour?

**Comment by amercader** [comment]
@Nithyavasudevan We are storing the whole error on the "value" field. We added the dataset metadata as well now in case we need it in the future
