### ISSUE TITLE
Mismatch between field length for tags field between CKAN and the platform

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#43]
The Tags field in the platform is Tags: string - comma separated list (optional, max 64000 chars total).

I tried to create a dataset with value in tags field of length 255 characters. I got the following error message.

"The form contains invalid entries:
•Tag string: Tag "maintainer name testeilrugilowekutbrgiloweubtrgiweutrbgiertbggritghbnreutgjbvieutrhgipeutrhgpiwutehgpiwuerghbnpiurtwpghbniwrutgphbniwrtugvbdefjvhbedjfhvbdvkfjbvdjkfbvdjkfbvdjkfbvjkdbfvdjkfvbtkjgnvdtkfjgnvrktjngrketgedfrjkgvnedekgvjdbnvkgjdfnithy1234567890" length is more than maximum 100"

![image](https://cloud.githubusercontent.com/assets/7315913/3189862/291f6ff8-ecc8-11e3-9aca-672f373d5a4c.png)

**Comment by Nithyavasudevan** [comment]
Seems like it has validation to check that a single tag value is 100 or less. i am able to add 2 tags (one of length 100 and one of length 2).

**Comment by amercader** [comment]
The maximum tag length in CKAN is 100 characters, and this is set at the db table level, so changing it would require significant effort. 

The spec mentions a combined max length of 64000, which we are enforcing [1], but does not limit the length of individual tags, so it seems like we are not deviating from it.

[1] https://github.com/okfn/ckanext-glasgow/blob/master/ckanext/glasgow/logic/schema.py#L161

**Comment by amercader** [comment]
Closing as it doesn't seem to be a defect. Feel free to reopen if you think otherwise.

**Comment by Nithyavasudevan** [comment]
Fine.
