### ISSUE TITLE
Unable to figure out how the tags field works

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#44]
Started creating a dataset and in tags field, entered the first tag value of length 99 characters followed by a comma. Now it doesn't let me enter a second tag value of length 99. It however lets me enter a tag value of length 98 followed by a comma. Then when I try to enter another tag value after the comma of length 98, it doesn't let me. It however lets me enter a third tag value of length 97 followed by a comma. Not sure I understand how this works.

**Comment by amercader** [comment]
@Nithyavasudevan I can add multiple tags of 99 characters to the tags field _as long as they different_. Are you using different tags?

**Comment by Nithyavasudevan** [comment]
Happy with unique check.
