### ISSUE TITLE
Add import commands for initial load of data

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-glasgow#45]
Related US #26, #27 

Write some paster commands that use the Metadata API to import all existing organizations and datasets in the platform to CKAN

See wiki pages for relevant requests / responses:

https://github.com/okfn/ckanext-glasgow/wiki/Sample-Datasets-from-EC-API
https://github.com/okfn/ckanext-glasgow/wiki/Organisation-responses-from-EC-API

There are functions in `logic/schema.py` to convert between CKAN / EC datasets

**Comment by amercader** [comment]
@joetsoi I should have mentioned, when creating / updating datasets via the importers pass `local_action` on the context, otherwise it will go via the request to the API path.

**Comment by nickstenning** [comment]
Done.
