### ISSUE TITLE
Update existing logic for updated endpoints

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-glasgow#46]
As of Iteration 2, there are two separate endpoints, one for POSTing stuff (port 8080) and one for GETing stuff (port 8081), we need to account for that when creating the request and on our mock EC API

Also the POST ones seem to require the Organisation now:

Create Dataset: /Datasets/Organisation/2 (instead of /Datasets)

Add a File to Dataset: /Files/Organisation/2/Dataset/3

Add a new File Version: /Files/Organisation/2/Dataset/3/File/b586e2f0-76ef-4620-b5ae-a0d929e9136e 

The existing functionality will break.

cc @adamamyl @joetsoi

**Comment by amercader** [comment]
Full endpoints here: https://github.com/okfn/ckanext-glasgow/wiki/EC-API-Endpoints

**Comment by adamamyl** [comment]
One thing to bear in mind is that eventually, each API will have its own hostname, not be served over ports; I don't know if we want to parameterize things or not.

**Comment by amercader** [comment]
The full hostname + port is parametrized for write (Data Ingestion) and read (Metadata) API endpoints. We can add more if needed.
