### ISSUE TITLE
As a SuperAdmin/Organisation Admin/Editor, I want to be able to initiate publication of a URL for an externally hosted file instead of providing a data file so that I can publish an externally hosted file.

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#47]
This is an amendment to:
- User Story #77 (US 1.2.1 As a Data Manager I want to be able to ingest files into the platform so I can add new files into an existing dataset.)
  - User Story #79 (US 1.2.3 As an Organisation Editor/Admin, I want to be able to initiate creation of a new version of an existing files in a dataset, so that I can create new file versions)

The users should be able to request creation of new files and new file versions, which content is located externally. Instead of supplying the file content, they supply a URL, where the content is located. This URL is saved on the platform and users downloading the file are required to manually fetch it from the external URL.
## API

This user story re-uses and extends the existing APIs for

 a) New file creation:

```
POST https://<hostUrl>/Files/Organisation/<organisationId>/Dataset/<DatasetId>
```

 b) New file version creation: 

```
POST https://<hostUrl>/Files/Organisation/<organisationId>/Dataset/<DatasetId>/File/<fileId> 
```

This user story is executed when the user supplies ExternalUrl (string, max 2000 characters) in the metadata in request JSON body and does not provide file content.

 The request to be well formed should be validated if:
- all mandatory metadata have values
- all provided values for pre-defined metadata should have valid type and satisfy validation rules defined for each metadata property
- if the request has file content, ExternalUrl metadata value is null or not provided
- if the request has no file content, ExternalUrl metadata value is provided and not null or an empty string
  
  If the user requests creation of a new external file, external file creation workflow is initiated (see US #1194)
## Business rules

 #. The platform stores external files URL only and does not download their content.
 #. External files URL is not verified to be correct (pointing to an existing file) and the external file is not virus scanned. The platform will only validate if the supplied ExternalURL is a valid URL (with schema: http, https or ftp).
 #. Update operation cannot change an external file to internal (stored on the platform) or vice versa.
 #. Different versions of the same file can be external or internal (stored on the platform).
### Publication of an external file (or file version)

Given :
- I'm authentication and I have suitable access rights
- the request is well formed
- I specify an external URL pointing to the file (instead of sending the file content)

When I request creation of a new file or a new file version
Then I receive a unique RequestID as JSON in the HTTP response with an HTTP Status of 200
## Standard HTTP REST API behaviour

The API follows standard HTTP REST APIs behaviour defined in NFR #891.
# OKF Effort

Test only.
## Accept Criteria
- [x] I can submit a file creation request via CKAN to initiate the publication of a URL to an external resource.
- [x]  I can only execute this request if I am an OrganisationEditior, OrganisationAdmin or SuperAdmin on the platform

**Comment by nickstenning** [comment]
Demoed today.

**Comment by adamamyl** [comment]
I3 Test Cases: Pass.
