### ISSUE TITLE
As an Anonymous User, I should be able to download an external file within a dataset so I can view the file

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#48]
This user story is an amendment to:
- US #246 (US R5.1.2 As an Anonymous User I should be able to download a specific version of a file within a dataset so I can view the file.)
- US #310 (US R5.1.3 As an Anonymous Data User I want to be able to download the latest version of an existing file within a dataset so I can view the file)
## API

This user story re-uses and updates the following API of Metadata service:

1) Downloading the latest file version:

```
http://<Hosturl>/Download/Organisation/<organisationId>/Dataset/<dataSetId>/File/<FileId>
```

2) Downloading a specific file version:

```
http://<Hosturl>/Download/Organisation/<organisationId>/Dataset/<dataSetId>/File/<FileId>/version/<versionId>
```

When the file is external, the user should be redirected (client redirect - 304 HTTP status code) to the external URL specified in file metadata instead of downloading the file content directly from the platform.
### Successful redirect to external URL

 Given
- a file metadata record exists which maps to `<organisationId>, <dataSetId>, <fileId>` (and `<versionId>` when a specific version is requested)
- the file is external

When the user requests file download,
Then the user is redirected to the URL specified for the external file (client-side temporary HTTP redirect - HTTP status code 307)
## Accept Criteria

Users when requesting to download a file, which is hosted outside of the platform, they are redirected to the external file URL.

**Comment by nickstenning** [comment]
Demoed today.

**Comment by adamamyl** [comment]
I3 Test Cases: Pass.
