### ISSUE TITLE
As an Authenticated User, I should be able to check the status of an asynchronous operation, so I can check if my operation completed successfully

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#50]
## OKF Notes

Status codes will let us track CKAN IDs against EC ids, and return this information to the user.

Could also provide information to org-admins telling them they have actions (Iteration 4) needing their attention.
## Acceptance Criteria
- [ ]  When I check an operation that has not yet completed (like create, etc), I should receive a message saying the operation is in progress
- [ ]  When I check an operation that has completed successfully, I should receive a message saying the operation completed successfully
- [ ] When I check an operation that has completed with a failure, I should receive a message saying the operation failed and It should show me the reason for failure.
## API

Metadata Service exposes the following operation:

`GET https://<HostUrl>/ChangeLog/RequestStatus/<requestId>`

The operation accepts a `<requestId>` returned by an asynchronous operation like creating a dataset, file, etc.

The response contains list of audit records in JSON format matching the specified requestId.
### User checking the status of an operation

Given I'm authenticated
 When I check the status of operation
 Than I receive all audits associated with specified requestId in a HTTP response with status 200 (OK).
## Standard HTTP REST API behaviour

The API follows standard HTTP REST APIs behaviour defined in NFR #891.
- When I check an operation that has not finished executing, I should eventually get the audit with information that the operation is in progress.
  - When I check an operation that has completed successfully, I should eventually get the audit with information that the operation completed successfully. I should see IDs of associated objects.
  - When I check an operation that has completed with failure, I should eventually get the audit with information that the operation failed. I should see the reason for failure.
### 1249
- Check the status of an operation
- display "processing" dialog
- display current status of resources
- Push to EC API
- On success create resource instance

**Comment by nickstenning** [comment]
@joetsoi has run in to some issues with authentication against the platform API here. Not demoed today.

**Comment by adamamyl** [comment]
Ready for Testing.

**Comment by adamamyl** [comment]
@Nithyavasudevan if you visit https://okfsandboxfe.cloudapp.net/dataset/test2finalds-5fac (as a logged in EC user) you'll see the 'Pending Resources' section.

Changing the URI to match a known request, will return that, too (organization etc).

**Comment by joetsoi** [comment]
The url for any given request is https://okfsandboxfe.cloudapp.net/request/<request_id> which will show the history of of that request.

**Comment by Nithyavasudevan** [comment]
This needs to stay open as there are defects raised with ability to check operation status depending on user role.

**Comment by Nithyavasudevan** [comment]
Closing this user story as any discrepancies are being tracked as defects separately.
