### ISSUE TITLE
As an Organisation Editor/Admin/SuperAdmin, I want to be able to initiate dataset predefined metadata update, so that I can correct dataset metadata

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#51]
## API

The Data Collection API for dataset creation will have this signature:

 `PUT https://<HostURL>/Datasets/Organisation/<OrganisationId>/Dataset/<DatasetId>`
 `<JSON body defining content>`

 All characters in Metadata properties are stored in UTF-8 format

 The predefined (mandatory and optional) metadata is supplied in JSON format:
  • Title: string (required, max 255 chars)
  • Description: string (required, max 4000 chars)
  • Maintainer Name: string (required, max 255 chars)
  • Maintainer Contact: string (required, max 255 chars)
  • License: string (required, max 255 chars)
  • Openness Rating: integer (required, range 0-5)
  • Quality: integer (required, range 0-5)
  • Tags: list of string (optional, max 64000 total)
  • Published on behalf of: string (optional, max 255 chars)

  Any text – no validation

 • Usage Guidance: string (optional, max 255 chars) 
 • Category: string (optional, max 255 chars)
 • Theme: string (optional, max 255 chars)
 • Standard Rating: integer (optional, range 0-5)
 • Standard Name: string (optional, max 255 chars)
 • Standard Version: string (optional, max 255 chars)

The operation returns a unique correlation ID.
## Business rules:
1. Organisation Editors/Admins can only update datasets in his/her organisation. SuperAdmins can update datasets in any organisation.
2. If optional metadata is not supplied their value is cleared.
3. If dataset title changes, it must be unique within its organisation (checked during dataset update workflow).
4. Dataset cannot be assigned to a different organisation.
   
   Scenarios
   
   Successful submission by Organisation Editor/Admin
   
   Given 
- I'm authenticated as Organisation Editor/Admin
- the request is well formed,
- specified `<organisationId>` is the same as my organisationId
  
  When I send dataset update request,
  
  Then:
- I receive a unique correlation ID as JSON in the HTTP response with an HTTP Status of 200
  - dataset metadata update workflow is initiated (see US #622)
  
  Successful submission by SuperAdmin
  
  Given I'm authenticated as SuperAdmin and the request is well formed,
  
  When I send dataset update request,
  
  Then:
- I receive a unique correlation ID as JSON in the HTTP response with an HTTP Status of 200
- dataset metadata update workflow is initiated (see US #622)
  
  Standard HTTP REST API behaviour
  
  The API follows standard HTTP REST APIs behaviour defined in NFR #891.
  ## Accept Criteria
- [x] As a Superadmin, i am able to successfully modify predefined metadata for any dataset in an organisation
- [x] As an Org Admin or Editor, I am able to successfully modify predefined metadata for any dataset within my own organisation only.

**Comment by joetsoi** [comment]
dataset metadata updates in 39dc5ea7df7c211ca713c7bece956bbc9d79417d

**Comment by mcginns** [comment]
User story accepted. This can be closed
