### ISSUE TITLE
As SuperAdmin, I should be able to initiate creation of a new organisation, so that new organisations can be added to the platform

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#52]
## API

Data Collection service should expose the following HTTP REST API to add new organisations:

`POST https://<hostUrl>/Organisations`
 `<JSON body defining metadata for organisation>`

 The body of the request should contain the following properties:
- Name (string, required, 2-500 characters)
- About (string, optional, max 4000 characters)

The description is expected to be in markdown format (no validation is required - every text is a valid markdown)

The API will be called only be authenticated users in SuperAdmin role.

The successful response will contain a unique request ID.
### Successful submission

 Given: 
- I have suitable access rights
- the request is well formed,
  
  When I send a organisation create request,
  Then:
- I receive a unique RequestID as JSON in the HTTP response with an HTTP Status of 200
  
  Standard HTTP REST API behaviour
  
  The organisation create API follows standard HTTP REST APIs behaviour defined in NFR #891.
### Comments:
1. Organisations must have unique names within the platform (it is checked as part of organisation creation workflow)
## Accept Criteria
- [ ] As a SuperAdmin can successfully create a new organisation.
- [ ] As an Org admin or editor I cannot create an organisation.

**Comment by nickstenning** [comment]
This story now includes the following item: when creating an organisation there should be a "dataset edits require approval" checkbox, which is used to pass on a boolean (`NeedsApproval, boolean (true/false), required`) to the Create Organisation API.

**Comment by mcginns** [comment]
User story accepted. This can be closed.

**Comment by mcginns** [comment]
Closed
