### ISSUE TITLE
As a SuperAdmin/Organisation Admin/Trusted Portal, I want to be able to initiate creation of a new user account on the platform so that the user can access the platform

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#53]
## Microsoft's API

Data Collection service should expose the following HTTP REST API to add new user account:

`POST https://<hostUrl>/Users{/Organisation/<organisationId>}`
`<JSON body defining metadata for user>`

The body of the request should contain the following properties:
- Username (without "@domain" part) - string, required, 1-16 characters, only digits, latin letters, dash (-), undescore (_) allowed
  - Password - string, required, 6-16 characters
  - Email - string, required, max 255 characters, must be a well formatted e-mail address
  - First Name - string, required, max 255 characters
  - Last Name - string, required, max 255 characters
  - Display Name - string, required, max 255 characters
  - About - string, optional, max 4000 characters

(CKAN note: split name field to first & last, and [weep](http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/))

The description is expected to be in markdown format (no validation is required - every text is a valid markdown)

The API will be called only be authenticated users and trusted external platforms (via client key authentication):
- SuperAdmins can create users in any organisation and global users (OrganisationId not specified or null)
- OrganisationAdmins can create users in their own organisation only
- If the caller is a trusted portal then only Member users can be created

The successful response will contain a unique request ID. 
### Successful submission

Given: 
- I have suitable access rights
- the request is well formed,

When I send a user create request,

Then:
- I receive a unique RequestID as JSON in the HTTP response with an HTTP Status of 200
### Organisation Admin creating global user or user in different organisation

Given: 
- I am an Organisation Admin
- I want to create a global user (OrganisationId=null) or a user in different organisation than mine
- the request is well formed,

When I send a user create request,
Then:
- I receive an error response (HTTP status code 403 - Forbidden) with error details.
### Trusted Platform tries to create

Given: 
- I am authenticated as a Trusted Portal,
- I want to create a user in a organisation
- the request is well formed,

When I send a user create request,
Then:
- I receive an error response (HTTP status code 403 - Forbidden) with error details.
### Standard HTTP REST API behaviour

The API follows standard HTTP REST APIs behaviour defined in NFR #891.
## Accept Criteria
- [ ] As a SuperAdmin I can create Organisation Editor users in any organisation
- [ ] As an Organisation Admin I can create Organisation Editor users in my organisation only.
- [ ] ~~As a SuperAdmin I can create Member users. They do not belong to any organisation~~
- [ ] ~~As an unauthenticated user of CKAN, I can register myself as a member user.~~

**Comment by seanh** [comment]
So if I understand this right, the request is not to automatically create the same user account on The Platform when a new user signs up in CKAN, but instead to add a new "Create users on The Platform" page to CKAN, where CKAN sysadmins and organization admins can create new user accounts on The Platform? And presumably these new accounts should be created in CKAN at the same time as well?

If I've understood it right the feature seems a little odd to me.

> If the caller is a trusted portal then only Member users can be created

Does "member user" here mean a user who is a member of an organization (in CKAN) but is not an editor, organization admin or sysadmin?

> The successful response will contain a unique request ID. 

Yay. Does this mean the user has been successfully created on The Platform? What can/should I do with the request ID?

What is a Trusted Platform/Trusted Portal?

**Comment by adamamyl** [comment]
> So if I understand this right, the request is not to automatically create the same user account on The Platform when a new user signs up in CKAN, but instead to add a new "Create users on The Platform" page to CKAN, where CKAN sysadmins and organization admins can create new user accounts on The Platform?

'Ordinary' (non municipal) users (datageeks, activists, journos, etc) should be able to create their own account to interact with data on the data.glasgow.gov.uk platform.

This should replace the 'normal' CKAN 'register' page (hitting the EC API that's detailed in the user story, and in the functional spec), so the user's created there (WAAD (username + password) & Identity Services (all other stuff) API)

In addition to that, there should be the ability for an Admin (sysadmin in ckan parlance) or org-admin (ckan parlance) to create users through CKAN (on the platform).

(I guess the 'invite' feature of CKAN organizations should reflect this behaviour, too.)

> And presumably these new accounts should be created in CKAN at the same time as well?

The plan is that CKAN doesn't have local accounts (bar the sysadmin/maintainer accounts), but caches info from the EC on login.

**Comment by adamamyl** [comment]
> > If the caller is a trusted portal then only Member users can be created
> > Does "member user" here mean a user who is a member of an organization (in CKAN) but is not an editor, organization admin or sysadmin?

A member user, means (unless I'm corrected), an ordinary user -- one who is not a member of an organization.

> > The successful response will contain a unique request ID.
> > Yay. Does this mean the user has been successfully created on The Platform?

Yes.

>  What can/should I do with the request ID?

Whatever you feel is the right action ;o) There's not much point storing it anywhere, unless there's a need to do this for CKAN's internal stuff.

> What is a Trusted Platform/Trusted Portal?

There's a concept that the EC will be used by multiple services, usually just hitting the read-only no-auth-needed APIs. There's also the concept that some portals/platforms are Special -- like our CKAN (as there could be other ckans) that have an identifier that grants special permissions (ability to use WAAD, access to some APIs, that sort of thing).

**Comment by adamamyl** [comment]
@adamamyl to seek clarification with @stevenlivz on this issue.

**Comment by adamamyl** [comment]
https://www.yammer.com/futurecitiesdemonstrator/#/Threads/show?threadId=420313501

**Comment by adamamyl** [comment]
PEBKAC. This issue is essentially to allow Org Admins / Admins to create WAAD users, via a form in CKAN.

**Comment by adamamyl** [comment]
Add in ability for SysAdmins to be created.

**Comment by Nithyavasudevan** [comment]
Can we please make sure this full requirement is understood in case i wasn't clear? Since we have done away with creating members on WAAD via CKAN, we need to understand how you would implement creating superadmin.

**Comment by adamamyl** [comment]
Quick note needed on Yammer re: specing out two-stage approach

**Comment by joetsoi** [comment]
@Nithyavasudevan. The ckan client key to create users atm. Using the users' key involves rewriting large sections of oauth2waad, the ckan client key cannot create users in organisations.

So I am looking to change it so that platform users are always created without organisations. After this, they can add users to organisations via the members page of an organisation. This would call the platform "change user role" call. This uses the user api auth token. 

There might be problems if an organisation admin cannot add a user with no organisation to their organisation.

**Comment by adamamyl** [comment]
> There might be problems if an organisation admin cannot add a user with no organisation to their organisation.

If user A is org-admin, for org. O, and tries to add user **U** to organization **O** what happens?

Can A add U, or does U need to be associated to O? (for the latter, my understanding is that this is allowed). @Nithyavasudevan can you test this via the test tool?

**Comment by joetsoi** [comment]
another option we have is  just ask microsoft to let the ckan client key have the ManageRegisteredUsers auth and then I can just get back to the super user form.

**Comment by Nithyavasudevan** [comment]
This is the list of permissible actions

SuperAdmin can request changing the roles and organisationId of any user 
Organisation Admin can request changing the roles of a user from their organisation only or being assigned to their organisation.
Organisation Admin can request assigning Member-only users to their organisation. They can also request un-assignment of users from their organisation.

SuperAdmin can create Member users
SuperAdmin can create Organisation Editor users in any organisation
Organisation Admin can create Organisation Editor users in their organisation only.

Does this make sense?

**Comment by stevenlivz** [comment]
Hi. Late to the party due to a million parallel thing :S Slightly confused on this one. When the user has logged in to ckan, do they not have a cached oauth token that could be passed as the bearer other than the ckan oauth token? From then the platform just picks up the user context for you? It may be more complex than this but it would be good to understand how it would change the existing oauth flow for a user - that way it can help me think about the options we have.

**Comment by joetsoi** [comment]
@stevenlivz, there are 3 user tokens, the current oauth token for users only handles 1. I changed the service to service tokens to handle the 3 tokens, but doing it for users would take a more significant amount of reworking of the oauth extension and in this one.

**Comment by stevenlivz** [comment]
Ok. I will follow up on this as i don't quite understand as all the other user api requests use the users oauth token but what about another direction on this one - maybe what you are already doing?

Use the ckan client key authentication to create a member user on the platform - so when logged in as organisation admin, you'd still use the ckan client key to create member users. Once this user has been created, the organisation admin can then change their role from Member to Editor within that organisation using the normal  logged in user permissions.

Does this make sense? I think it is aligned with your earlier suggestion.

**Comment by amercader** [comment]
This is ready on the CKAN side, but the platform is returning errors when trying to create a user:

```
State - Failed
Timestamp - 2014-09-09T13:04:57.0891619Z
Type - User
Message - User 'davidsmith' was not created - 'An error has occurred validating input passed to the method.'.
```

**Comment by Nithyavasudevan** [comment]
what was the data passed please?

**Comment by Nithyavasudevan** [comment]
works
