### ISSUE TITLE
As a SuperAdmin/Organisation Admin, I want to be able to update user roles, so I can manage permissions on the platform

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#55]
## API

The Data Collection Service should expose the following HTTP REST API to update user roles and organisation assignment:

 `PUT https://<HostURL>/UserRoles{/Organisation/<organisationId>}/User/<userId>`

`<JSON body containing new roles for the user>`

The body should contain JSON encoded:
- NewOrganisationId, string, optional; This must be set to the users current or new organisation. If the user will not be in an organisation then this is null or not included.
- list of roles the user should be member of.
## Permissions

The API will be called only by OrganisationAdmin or SuperAdmin users:
- SuperAdmins can change roles and organisation of users in any organisation and global users (OrganisationId not specified)
- Organisation Admins can change roles of users in their own organisation only; they can only assign organisation-level roles (OrganisationAdmin, OrganisationEditor)
- Organisation Admins can assign users to their organisation by specifying NewOrganisationId. The users assigned to their organisation must be global (not assigned currently to any organisation) and can have Member role only.
- Organisation Admins can remove users from their organisation by setting NewOrganisationId to null.
  ## Business rules:
  1. User assigned to an organisation can have only organisation-level roles (Organisation Editor/Admin).
  2. User not assigned to an organisaion can have only global roles (Member, SuperAdmin).
  3. Users must be assigned to at least one role.
  4. Last SuperAdmin cannot have the SuperAdmin role removed.
  5. An OrganisationAdmin cannot remove the last OrganisationAdmin role for their organisation.
- When no roles are specified, a default role is assigned:
- Member for a user not assigned to an organisation (NewOrganisationId not specified)
- OrganisationEditor for a user assigned to an organisation (NewOrganisationId specified)
  ## Scenarios:
### Successful reception

Given 
- I have suitable access rights (as defined in permissions section)

When I send an update user roles request,
Then:
- I receive a unique RequestID as JSON in the HTTP response with an HTTP Status of 200
### Invalid roles assignment

Given 
- I have suitable access rights
- I want to: 
  - assign an organisation-level user (NewOrganisationId is set) a global role (Member or SuperAdmin) or
  - assign a global user (NewOrganisationId in null) and organisation-level role

When I send an update user roles request,
Then:
- my request is rejected (HTTP status code 400 - Bad Request) with an explanation Standard HTTP REST API behaviour

The API follows standard HTTP REST APIs behaviour defined in NFR #891.  
## Accept Criteria
- [ ] As a SuperAdmin I can request changing the roles and organisationId of any user in any organisation
- [x] As an Organisation Admin I can request changing the roles of a user from my organisation or to my organisation only
- [ ] As an Organisation Admin I can request assigning Member-only users to my organisation. I can also request un-assignment of users from my organisation.

**Comment by adamamyl** [comment]
See also MS US 1365

**Comment by adamamyl** [comment]
Essentially, for CKAN implementation, hit the EC's Identity Services API to set/change/remove organization members

**Comment by adamamyl** [comment]
https://github.com/okfn/ckanext-glasgow/issues/54#issuecomment-49134294 may be of relevance here, though this is largely going to be EC based -- except, maybe when a user is removed from an organization, and becomes a member (edge case scenario?)

**Comment by adamamyl** [comment]
This user story relates to EC users.

**Comment by joetsoi** [comment]
unassignment of users currently makes no sense? As a EC user _must_ be the member of an organization.

e: this currently jst overrides member_create/member_delete. This means you will not be able to add/remove ckan users to an organization.

**Comment by Nithyavasudevan** [comment]
@joetsoi not sure if this helps, but there are member users within EC who are not assigned to any organisation. They are no different to an anonymous user in terms of the permissions on the platform. They can at some point be pulled into an organisation by changing roles..

**Comment by adamamyl** [comment]
In the Accept Criteria we have

> As an Organisation Admin I can request assigning Member-only users to my organisation. I can also request un-assignment of users from my organisation.

This criterion pre-dates the decision we reached that Members will not be in the EC. To that extent, I think this accept criteria should be re-defined to

_As an Organisation Admin I can request un-assignment of users from my organisation._

Is that acceptable, @stevenlivz @Nithyavasudevan ?

**Comment by Nithyavasudevan** [comment]
I think there is still an opportunity for members to be on EC. I don't think we are absolutely ruling that out. There will still be member users on EC. @stevenlivz ?

**Comment by joetsoi** [comment]
well there are a few issues, firstly there is not an easy way of differentiating between EC users and ckan users from ckan's point of view. Assuming we can get past that, then from the someone actually using the interface, it's now not clear what happens when I click the member delete button, sometimes it will return me a request id(ec user), sometimes it'll remove the user(ckan user)

Additionally what happens if I add a user to a group? Some users (from ckan) will jsut be added to the group and some users (ec users) will have their group totally changed after they are returned a request id.

I could seperate out the interfaces and just have a separate interface for changing roles for EC users, but this makes group management much more difficult as there are now two places to manage users and I'll have to check which ones are EC users or I don't know at all, and when adding members to groups, I'll have to try two places and hope I get the right place first.

I know what an EC users is, I know what a ckan user is, but will whoever is actually using the site know?

**Comment by joetsoi** [comment]
I've deployed what I have so far to staging and I'm getting timeout for the api call, is this the same for you @Nithyavasudevan (/UserRoles/Organisation/{organization_id}/User/{user_id}), otherwise I'll need some sample output of how the changelogs will look like, otherwise I can't write the code for harvesting these updates in the changelog.

**Comment by Nithyavasudevan** [comment]
Can you let me know exactly what you are trying to do please? I am able to update user roles..

**Comment by joetsoi** [comment]
@Nithyavasudevan, a second set of eyes would be great, this is the request being sent and the json being sent along with it, i'm getting 500s

```
[Thu Aug 07 12:15:05 2014] [error] 2014-08-07 12:15:05,378 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): gccctpecdatacollectionservicesint.cloudapp.net
[Thu Aug 07 12:15:05 2014] [error] 2014-08-07 12:15:05,724 DEBUG [requests.packages.urllib3.connectionpool] "PUT /UserRoles/Organisation/6c036197-f4f3-4396-8560-cd942db3b7ba/User/39de8811-b9a1-4929-9c78-0d25efbf8c41 HTTP/1.1" 500 36
[Thu Aug 07 12:15:05 2014] [error] 2014-08-07 12:15:05,724 DEBUG [ckanext.glasgow.logic.action] request data: {"UserRoles": {"UserGroup": ["OrganisationEditor"]}}
```

**Comment by Nithyavasudevan** [comment]
Is this the user id 39de8811-b9a1-4929-9c78-0d25efbf8c41 ?

I can't seem to find it in the db..
can you try this? 
PUT /UserRoles/Organisation/C3220A9C-B0E5-4594-A33A-1F9F144419E7/User/CAABC9C3-DAEC-4967-A48D-A96E5068FA2D HTTP/1.1

**Comment by joetsoi** [comment]
ah ok, I've fixed it to use the  EC user ids, it should have been calling ae93f7fc-27e3-40a6-b3c0-0872cd579bf2 is that user in the database?

I can't try for that user id (CAABC9C3-DAEC-4967-A48D-A96E5068FA2D) as we haven't set up syncing of users from EC to ckan yet, so it's not curreently in the ckan database on staging.

**Comment by Nithyavasudevan** [comment]
No.. can't find him in the db. I will email you the users in db..

**Comment by adamamyl** [comment]
Issue with "null" as Username causes this to error.

**Comment by mcginns** [comment]
Accepted. User Story closed.
