### ISSUE TITLE
As a SysAdmin I want to be able to process and view EC Audit activity

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#56]
See also #50 and [Microsoft User Story 1305](https://docs.google.com/a/okfn.org/spreadsheets/d/1vE6hKWnLPv7s60RFDpXKuvxhuQWoPWUK0NRaR1rPiU8/edit#gid=0)

Initial thoughts for implementation
- Request updates made in platform (API request)
- harvest changes into CKAN
- enumerate the resource types (organizations, datasets, files, users)
- detect CUD (change, update, delete) changes 
- populate data into CKAN
- Store last audit ID against each object type
  - organization
  - users / roles
  - dataset metadata
  - file metadata

**Comment by seanh** [comment]
So the feature is to add a page to CKAN, visible to sysadmins only, that calls this ChangeLog URL of the Metadata Services API and displays all the items that it gets back? Presumably "EC Audit activities" are the "successful audit records" that the ChangeLog URL from MS user story 1305 returns?

What does "processing" the EC Audit activity mean?

Also what's the HostUrl that I can use to test the API calls against? And how to I authenticate to it? (I think @amercader can answer that last one)

**Comment by adamamyl** [comment]
> So the feature is to add a page to CKAN, visible to sysadmins only, that calls this ChangeLog URL of the Metadata Services API and displays all the items that it gets back? Presumably "EC Audit activities" are the "successful audit records" that the ChangeLog URL from MS user story 1305 returns?

Yeap.

> What does "processing" the EC Audit activity mean?

Extract, Transform, Load / Get from the EC and stuff it somewhere CKAN can make sense of/use. It may be worth noting that the EC will not store all logs over a period of time, and that there will be (on the EC) some clear out -- at least in the current design.

> Also what's the HostUrl that I can use to test the API calls against? And how to I authenticate to it? (I think @amercader can answer that last one)

[The Functional Spec](https://docs.google.com/a/okfn.org/document/d/1fBMkQV1Fj_07M-Rg-MqafTnQQLXlkVHxpSyONeDARkQ/edit#heading=h.2pta16n) details the nitty gritty. HostURL should [end up in your inbox](https://www.yammer.com/futurecitiesdemonstrator/#/Threads/show?threadId=412201391)

**Comment by nickstenning** [comment]
To clarify:
- The important part here is worker process (probably run in a cron job or as a daemon) which runs through unseen items in the changelog and applies the described changes to the CKAN database
- There is _no_ requirement for UI
- How much of the changelog does the worker need to process? A simple rule: if we know how to make a request to the platform for a particular kind of change (dataset create, file update, etc.) we should know how to process the corresponding typed changelog entry.

**Comment by amercader** [comment]
_Implementation proposal_

Reuse harvesting framework. Even if it is generally used just for datasets, nothing prevents us from handling other objects at the `import_stage`, and we get the Redis queue, persistence of remote objects in the DB, error handling, etc for free.

**Requirement**: Implement [Service to Service](http://msdn.microsoft.com/en-us/library/azure/dn645543.aspx) authorization on [ckanext-oauth2waad](https://github.com/ckan/ckanext-oauth2waad) to handle authentication from the harvester.
- Gather stage:
  - Call `ChangeLog/RequestChanges/<last_audit_id>` and store a Harvest Object for each Audit object
  - We no longer need to filter any operations coming from CKAN as all objects will be created with this mechanism.
  - Store the last Audit Id so we know where to start next
    
    Q: Where? (custom table with link to harvest job id?)
- Fetch stage:
  - Do nothing
- Import stage:
  - For each harvest object / audit (stored during the gather stage), get the contents and check the `Command` value.
  - Depending on this value call different functions registered to handle each type of command (create dataset, update org, delete user, etc). These actions will call the Metadata API with the Ids provided in `CustomProperties` to get the latest version of the object.
  - Whenever possible, we will store the `AuditId` against the CKAN object. For datasets, files and orgs that can be an extra.
    
    Q: What about users?
  - Q: Do we need to update the `TaskStatus` table on each object action for those Audits that were originated from CKAN? Or this will be handled separately via #50 (in this case there might be a slight delay until the changes take actually place in CKAN)
  - The only thing that will be needed to be handled differently than a regular harvester is that we will only set `package_id` and `current` on the harvest object table when the operation refers to Datasets and Files (if we can get the `package_id` easily). For orgs and users we will leave these fields empty as they don't need to be taken into account for reports anyway.

@joetsoi @nickstenning let me know your thoughts

**Comment by nickstenning** [comment]
What does reusing the harvest framework imply for the frequency at which updates are pulled in? Ideally this would be running every few minutes (or even every minute).

**Comment by amercader** [comment]
We can write a small wrapper function around the one used by the harvesting extension that will run the thing every X minutes.

**Comment by nickstenning** [comment]
In which case, this sounds eminently sensible to me.

**Comment by adamamyl** [comment]
Exposing aspects of change log deployed through a variety of endpoints.
