### ISSUE TITLE
Unable to see all organisations in the platform on CKAN

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#57]
Opened "https://ckanfrontend.cloudapp.net/organization" as an anonymous user. Am able to see only 93 organisations. A manual harvest was triggered by Adam at 11.30 am. Its 12,10. I still don't see all the organisations. Number of organisations in the platform = 109

![image](https://cloud.githubusercontent.com/assets/7315913/3339456/5e6f0196-f86c-11e3-8e34-96b0cd1410d0.png)

**Comment by amercader** [comment]
As of this comment timestamp there are 108 organizations defined in the platform. 15 of these are duplicates (which sounds like a bug and should be not allowed):

108 - 15 = 93

List of duplicates:

```
Edinburgh Business School
State Bank of India
Indian Bank
State Bank of Saurashtra
State Bank of Travancore
State Bank of Patiala
State Bank of Mysore
State Bank of Hyderabad
State Bank of Bikaner & Jaipur
State Bank of Saurashtra
State Bank of Travancore
State Bank of Patiala
State Bank of Mysore
State Bank of Hyderabad
State Bank of Bikaner & Jaipur
```

**Comment by Nithyavasudevan** [comment]
All these were entered directly on the database. So no bug in platform. So CKAN validates results coming back from the API before displaying on screen?

**Comment by Nithyavasudevan** [comment]
Happy to close based on message from Adria that some validation does happen when harvesting data from the platform.
