### ISSUE TITLE
1 organisation appears at the bottom of the CKAN home page

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#58]
Opened the page "https://ckanfrontend.cloudapp.net/". On the home page one of the organisations is displayed at the bottom of the screen.

![image](https://cloud.githubusercontent.com/assets/7315913/3339799/373ae372-f873-11e3-9147-ddd87bfe9756.png)

**Comment by adamamyl** [comment]
This was a 'homepage' option (at the bottom of https://ckanfrontend.cloudapp.net/ckan-admin/config), featuring an organization/dataset.

I've adjusted it to not show that.

**Comment by Nithyavasudevan** [comment]
Can you please not close any of my issues until agreed with me please?

I am not sure I understand what this homepage option is.. I could not find it on the data.glasgow site. Is it a requirement?

**Comment by amercader** [comment]
A plain CKAN (without any customizations) will display a column on the left with a featured Group and its datasets and a column on the right with a featured Organization and its datasets (See eg http://demo.ckan.org/). There are no groups in this server so a single org is shown.

You can change this setting between a set of predefined layouts in the [config page](https://ckanfrontend.cloudapp.net/ckan-admin/config), which is what adam was referring to.

This is just what a default installation of CKAN will display and purely a cosmetic issue that can be ignored until the theming of the instance is tackled. I'd expect the whole homepage to be customized as in http://data.glasgow.gov.uk/.

**Comment by Nithyavasudevan** [comment]
happy with explanation. can be closed.
