### ISSUE TITLE
All datasets not displayed in dataset page

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#59]
The platform has 15 datasets. When I open the datasets page as an anonymous user, I am able to see only 7 datasets. The manual harvest for data was done by Adam at 11.30am. Time is now 13.16. Still no new datasets.

![ckan datasets](https://cloud.githubusercontent.com/assets/7315913/3340248/f8ccf12c-f87a-11e3-895e-0e9f61d36118.png)

**Comment by adamamyl** [comment]
@joetsoi

**Comment by amercader** [comment]
Some of the missing ones are caused by the validation failing in the harvesting process, specifically an inconsistency in how the file URLs are defined in the EC API (`ExternalFileUrl` vs `ExternalUrl`). Some others seem to be actually missing, so we need to investigate.

**Comment by joetsoi** [comment]
datasets with the same name can cause a validation error it seems, we can attach the org id and/or dataset id to the dataset name for the url. 

If microsoft had really long org ids we'd run into trouble again, perhaps we should just use the package id ckan generates in these cases

**Comment by Nithyavasudevan** [comment]
Org ID's will be guid in Iteration 3 on the platform. Dataset titles within an organisation should be unique. No unique check is required across organisations if that makes sense?

**Comment by joetsoi** [comment]
I've added the id of the org onto the end of a dataset, so names don't clash. There will be a problem if the org ids are long (more than 100 characters) as we use the dataset name part of the url in ckan. We can probably just get away with upping the number of characters in the validator.

**Comment by amercader** [comment]
Sandbox now displays the correct number of datasets (83 as of now on the platform).

https://okfsandboxfe.cloudapp.net/dataset

**Comment by adamamyl** [comment]
Ready to close?
