### ISSUE TITLE
Metadata on a dataset not harvested from the platform

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#63]
On trying to view the metadata for a dataset most of the metadata values are not retrieved from the platform. Some values (Maintainer Name and Email) are retrieved. This is user story 28

![image](https://cloud.githubusercontent.com/assets/7315913/3342434/8bf4f10e-f892-11e3-9dc2-7c3b96cf5051.png)

**Comment by amercader** [comment]
The metadata is harvested, but due to a mistake in the deployment was not shown in the frontend. Should be fixed now, see eg:

https://ckanfrontend.cloudapp.net/dataset/test-dataset-org2

https://ckanfrontend.cloudapp.net/dataset/this-is-a-dataset

**Comment by Nithyavasudevan** [comment]
this works fine now
