### ISSUE TITLE
Visibility is not a value GCC use on a dataset

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#67]
1. Logged in as SuperAdmin and navigated to create dataset screen.
2. Note the Visibility dropdown with values Private & Public.
3. This is not a field required by GCC and this field should not be present. All datasets are public by default.
   ![image](https://cloud.githubusercontent.com/assets/7315913/3355641/98c543d2-fab5-11e3-9e40-9ad36d699d71.png)

**Comment by amercader** [comment]
This field was mentioned on a few occasions on the preliminary tech discussions so that's why we kept it, but we'll hide it straight away.
