### ISSUE TITLE
Unable to create dataset with valid login details

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#68]
1.Logged in as SuperAdmin and navigated to dataset creation page
2. Entered all values needed for creating a dataset and hit submit
3. Got an EC auth error
![image](https://cloud.githubusercontent.com/assets/7315913/3355702/784ce03c-fab6-11e3-82cd-6b4f38815217.png)

**Comment by amercader** [comment]
@Nithyavasudevan can you try creating a dataset under the "Aberdeen School of Art" organization?

https://ckanfrontend.cloudapp.net/organization/aberdeen-school-of-art

See https://github.com/okfn/ckanext-glasgow/issues/66#issuecomment-46840463 for what might be going on.

**Comment by Nithyavasudevan** [comment]
I tried for Aberdeen School of Art as it was the only one and got the above message. But i am guessing you need to add my uid to that dataset?

**Comment by amercader** [comment]
OK, I think the configuration is now properly set up in the integration server. You will need to log off and restart the browser to be able to login again in the WAAD server.

When testing with the "Editor GCC2" user (I don't have the credentials for the superadmin one) I get this, which is a 500 error on the EC API:

![screenshot from 2014-06-23 14 31 42](https://cloud.githubusercontent.com/assets/200230/3358176/080acfda-fadb-11e3-85a1-a86795cb0859.png)
:

**Comment by Nithyavasudevan** [comment]
seems to work now
