### ISSUE TITLE
No link to upload a file

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#69]
1. Login as SuperAdmin and navigate to dataset screen
2. Click on a dataset and then on the "why not add some" link on the next page so it takes you to the screen to add files
3. Fill in the mandatory values and click add.
4. You get an error message saying Upload: No file uploaded
5. But there is no link on the screen to actually upload a file
   ![image](https://cloud.githubusercontent.com/assets/7315913/3356162/04083468-fabd-11e3-8bdc-b16d57715d51.png)

**Comment by amercader** [comment]
Sorry, a mistake during deployment, should be fixed now. Note that the "Link" option will not work until #47 is implemented on both sides.

**Comment by Nithyavasudevan** [comment]
able to upload now
