### ISSUE TITLE
Harvest extension config files don't get deployed on Ansible script

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-glasgow#73]
[This](https://github.com/okfn/ckanext-glasgow/blob/master/deployment/roles/ckanext-harvest/tasks/main.yml#L21:L26) does not seem to work

@nigelbabu can you have a look

**Comment by nigelbabu** [comment]
This is because the files associated with a role needs to go into the role's files directory.

**Comment by amercader** [comment]
@nigelbabu did you get round to do this? If so can you push it please? Thanks

**Comment by nigelbabu** [comment]
It worked for me on a different server without any changes. I'll merge the
config of the server into the repo and try a push tomorrow.

Nigel Babu
Developer, Open Knowledge

**Comment by amercader** [comment]
This works as expected, sorry for the confusion
