### ISSUE TITLE
Description field lengths don't match between the platform and CKAN

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#78]
In the file upload screen, description value takes only 4000 characters. On the platform, the field length is 64000 characters.
So this will need to be changed.

**Comment by amercader** [comment]
I assumed that to be a typo, as the description of the datasets has a max value of 4000. We can set it to 64k, of course, but it hard to think of sane use case for adding a description so long to a file.

**Comment by Nithyavasudevan** [comment]
It isn't a typo.. It is 64k on the platform
