### ISSUE TITLE
Harvest every 30mins

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#80]
Can we schedule the harvester(s) to run every 30 minutes in the Integration environment only -- to pull information about organizations, datasets, metadata, files etc.

**Comment by Nithyavasudevan** [comment]
yes.. fine by me..

**Comment by adamamyl** [comment]
(I created this task based on the issue logged in the Action Log)

**Comment by amercader** [comment]
Hourly is the lowest that you can schedule in the harvest extension.

One important thing to note is that the harvester in its current form is only meant to provide an initial snapshot of the existing orgs, datasets and files on the platform, not to keep track of changes. This would be done at a latter stage, using the Platform Change Log endpoints (or upgrading this one to the new requirements). In the meantime, the current harvester will still work to sync orgs and datasets between platform and CKAN, but not in a very efficient way (will pull the whole lot each time, doesn't account for deletions, ...). So eventually the current harvester will get replaced by the changelog based one.

/cc @joetsoi

**Comment by nickstenning** [comment]
Is there any remaining work to do here? If the smallest interval is 1h, let's set it to that and be done with it.

_Big proviso: I have no idea what the requirements are here, I'm just keen that we close noise tickets_

**Comment by Nithyavasudevan** [comment]
I would suggest not spending any more time on this as this will get replaced once we have changelog in place on the platform (which is Iteration3)

_Just my thoughts_

**Comment by amercader** [comment]
Turns out I was wrong and daily is the lowest the harvest extension will accept. I've created an issue there to add the Hourly option (ckan/ckanext-harvest#98).

In the meantime it is set to daily, and harvests can be triggered manually.

**Comment by stevenlivz** [comment]
Is this for general sync? I think that would need to be 15 mins or so - or an approach that would allow triggering at a custom threshold. Should discuss.

**Comment by stevenlivz** [comment]
Never mind - Nithya talked with me.
