### ISSUE TITLE
As SuperAdmin/Organisation Admin, I should be able to initiate update of an organisation

### ISSUE THREAD

**Issue by nickstenning** [okfn/ckanext-glasgow#83]
As a SuperAdmin or Org Admin, I should be able to update the organisation, and the result should be a call to the platform API:

```
PUT https://<hostUrl>/Organisations/<OrganisationId>
```

 The body of the request should contain the following properties:
- Name (string, required, 2-500 characters)
- About (string, optional, max 4000 characters)
- NeedsApproval, boolean (true/false), required

The description (`About`) is expected to be in markdown format (no validation is required). The NeedsApproval boolean should be exposed in the UI as "dataset modifications for this organisation require approval" or similar wording. See also #52.

The ability to update organisations should only be available to authenticated users as outlined below:
- SuperAdmins can update any organisation
- Organisation Admins can update only the organisation they belong to.

The successful response will contain a unique request ID.
### Comments:
1. Organisations must have unique names within the platform
## Accept criteria
- [ ] As Super Admin I am able to update metadata (including org name) of any organisation The updates are successful if the org name still remains unique.
- [ ] As Org Admin I am able to update metadata (including org name) of my own organisation. The updates are successful if the org name still remains unique

**Comment by mcginns** [comment]
Operates as expected for both SuperAdmin & OrgAdmin
