### ISSUE TITLE
As a publisher, I want to be able to provide custom metadata for files, so that I can enrich file metadata with custom fields

### ISSUE THREAD

**Issue by nickstenning** [okfn/ckanext-glasgow#84]
An amendment to the UI and payload associated with resource creation.

The UI should allow the creation of arbitrary key-value metadata associated with a specific resource, _in addition to_ the fields defined in the extras schema. The extras data should be passed to the "platform API" according to the following specification:

> The file create/update API bodies can additionally contain any number of custom metadata properties. Each property will be a key-value pair:
> - Key: string (required, not empty, max 255 chars)
> - Value: string (optional - can be empty, max 64000 chars)
> 
> Keys must be unique (case insensitively) and cannot have the same names as pre-defined metadata properties (case insensitively)
> The custom metadata should be saved/updated along with pre-defined metadata.
## Accept criteria
- [ ] Custom metadata are created for the file and am able to view them on CKAN front end

**Comment by amercader** [comment]
Deployed to integration, ready for testing

**Comment by Nithyavasudevan** [comment]
The testing for this is blocked by issue 119. I can't seem to submit file updates.

**Comment by adamamyl** [comment]
Needs user roles and perms in place (see #53)
