### ISSUE TITLE
As a publisher, I want to be able to provide custom metadata for datasets, so that I can enrich dataset metadata with custom fields

### ISSUE THREAD

**Issue by nickstenning** [okfn/ckanext-glasgow#85]
An amendment to the UI and payload associated with dataset creation.

The UI should allow the creation of arbitrary key-value metadata associated with a specific dataset, in addition to the fields defined in the extras schema. The extras data should be passed to the "platform API" according to the following specification:

> The dataset create/update API bodies can additionally contain any number of custom metadata properties. Each property will be a key-value pair:
> - Key: string (required, not empty, max 255 chars)
> - Value: string (optional - can be empty, max 64000 chars)
> 
> Keys must be unique (case insensitively) and cannot have the same names as pre-defined metadata properties (case insensitively)
> The custom metadata should be saved/updated along with pre-defined metadata.
## Accept criteria
- [ ] Custom metadata are created for the dataset and am able to view them on CKAN front end

**Comment by amercader** [comment]
Deployed to integration, ready for testing

**Comment by Nithyavasudevan** [comment]
this works in general.

**Comment by adamamyl** [comment]
Needs user roles and perms in place (see #53)
