### ISSUE TITLE
As a SuperAdmin/Organisation Editor/Admin, I want to be able to initiate update of a file in a dataset (content and predefined metadata), so that I can replace an existing version of the file

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#87]
## Microsoft API:

The Data Collection API for file version update will have this signature:

```
PUT https://<HostURL>/Files/Organisation/<OrganisationId>/Dataset/<DatasetId>/File/<fileId>/Version/<versionId>
<JSON body defining metadata and file content>
```

The body may contain the following predefined metadata (optional and mandatory):
- Title: string (required, max 255 chars);
- Filename: string (required, max 255 chars) &#8212; Must conform to standard file name conventions and is url encoded and is not case sensitive; Validation regex: `^[^\p{Cc}<>:""\/\\|?*]+$`
- Description: string (required, max 64K chars)
- Type: string (required, max 255 chars)
- Creation date: date and time in UTC timezone (optional)
- License: string (optional, max 255 chars)
- Openness Rating: integer (optional, range 0-5)
- Quality: integer (optional, range 0-5)
- Standard Rating: integer (optional, range 0-5)
- Standard Name: string (optional, max 255 chars)
- Standard Version: string (optional, max 255 chars)

The successful response will contain a unique request ID.
### Successful submission

Given: 
- I have suitable access rights
- the request is well formed,

When I send a file version update request,
Then:
- I receive a unique RequestID as JSON in the HTTP response with an HTTP Status of 200
## Standard HTTP REST API behaviour

The file version metadata update API follows standard HTTP REST APIs behaviour defined in NFR #891.
## Comments:
1. Concurrent update checking is out of scope. If there are 2 concurrent updates of the same version of the file, the last update overwrites the first one.
2. File Version has to be always specified. Update of ""latest version"" (without specifying the version) is not supported.
3. New file metadata will completely overwrite existing metadata. If an optional property (like Quality) is not provided, the updated file version will not have quality attribute.
4. External file (with URL pointing outside the platform) cannot be changed to internal (with content stored on the platform) and vice versa.
## Accept Criteria

When I have suitable access rights and I send a valid request, I can initiate a file metadata and content update and I should receive a unique request ID.

**Comment by Nithyavasudevan** [comment]
works
