### ISSUE TITLE
US 9.1.16 As an Authenticated user, I want to be able to get user information, so I can see user's profiles

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#88]
## Microsoft API

Identity service should expose the following HTTP REST API:

```
GET https://<hostUrl>/Identity/User/<userName>
```

The successful response should contain the following profile information
- UserName - string, the name of the user
- UserId - string (GUID), internal user's identifier
- OrganisationId String (GUID) Id of the users organisation
- Email - string
- First Name - string
- Last Name - string
- Display Name - string
- About - string
## Permissions:

The API will be called only by authenticated users:
- SuperAdmins and Trusted portal can get users' metadata in any organisation and users without any organisation (registered or management)
- Organisation Admins can get users' metadata from their organisation
- Authenticated users can get only their metadata
### Successful submission

Given:
- I have suitable access rights
- the user of specified username exists in metadata database (case insensitively)

When I retrieve user profile metadata,
Then:
- I receive user's profile metadata with an HTTP Status of 200 (case insensitively)
### User does not exist

Given:
- I have suitable access rights
- the user of specified username does not exist in metadata database

When I retrieve user profile metadata,
Then:
- I receive an unsuccessful response with HTTP status code 404.
## Standard HTTP REST API behaviour

The API follows standard HTTP REST APIs behaviour defined in NFR #891.
## Accept Criteria
- [ ] SuperAdmin or Trusted Portal can retrieve any existing user's profile metadata.
- [x] Organisation Admin can retrieve users profile metadata from their organisation.
- [x] Authenticated user can retrieve their own profile metadata.

**Comment by joetsoi** [comment]
I'm currently getting 404s for this endpoint. @Nithyavasudevan does this endpoint work for you?

**Comment by Nithyavasudevan** [comment]
This is giving me an error along with fetch all users too. I have already informed Jakub. Will let you know what he says,,

**Comment by Nithyavasudevan** [comment]
just to note though.. i am getting an internal server error.. not a 400..

**Comment by joetsoi** [comment]
ok, maybe I'm using the wrong url, I'm currently using 

```
https://gccctpecmetadataservicesint.cloudapp.net/Identity/User/OrgAdminGCC2@GCCCTPECADINT.onmicrosoft.com
```

is this different to yours?

**Comment by Nithyavasudevan** [comment]
am guessing it should use identity services rather than metadataservice in the url? one sec

**Comment by Nithyavasudevan** [comment]
```
https://gccctpecidentityservicesint.cloudapp.net/Identity/User/{User}
```

**Comment by joetsoi** [comment]
did jakub ever get back to you?

I've added 3 action functions ec_user_show, ec_user_list, ec_user_list_for_organization which proxy requests to the ec platform.

I'm currently getting unauthorized errors for them, you can test them on staging

e.g http://okfstagingfe.cloudapp.net/api/action/ec_user_list

**Comment by joetsoi** [comment]
ec_user_list now works, but all the users have their username = null.

The api for fetching users https://api.end.point/Identity/User/<username> wants the userName as a parameter, I've tried substiuting userId but that returns a 404, so I'm guessing it only works for userNames. I'm guessing the endpoint is actually working, it's just that the current test data means it's not usuable at the moment. 

@Nithyavasudevan, have you tested this endpoint as well?

**Comment by adamamyl** [comment]
Issue with "null" as Username causes this to error.

**Comment by Nithyavasudevan** [comment]
there is no link to view all users in the system. only way now is to go into each organisation and look at members

**Comment by mcginns** [comment]
List of users available via

![image](https://cloud.githubusercontent.com/assets/7511445/4303564/374daf1c-3e68-11e4-9999-b90b317b049d.png)

which is ok (albeit you need to go own user first then click back to home / users or browse straight to the url ...cloudapp.net/user)

User profile information can be viewed so ok to close this story.
