### ISSUE TITLE
As a SuperAdmin/Organisation Admin, I want to be able to view files and datasets awaiting my approval, so I can approve or reject the operation

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#91]
## Microsoft API

The data collection service should expose the following REST API:

`GET https://<HostURL>/Approval?<paging parameters>`

`<paging and sort parameters>` are:
- $top - the size of page to return. &#8212; If parameter is omitted, the default value is 100. Minimum page size is 1 and maximum page size is 100. If the user specifies value outside this range, it is treated as if they've entered the default value (100).
- $skip - the number of top items to skip in the results. &#8212; If parameter is omitted, the default value is 0. Minimum value is 0. If the user specifies value lower than minimum value (0), it is treated as if they've entered the minimum value.

The successful response should contain a JSON-encoded list of operation's awaiting user's approval sorted by created date.

Each list item should contain the following fields:
- RequestId, String - request unique identifier
- CreatedDate, Datetime - the date the approval request was raised
- Command, string - name of command
- ObjectType, string - type of object for approval: File or DataSet
- Metadata - dictionary of object's metadata
- OrganisationId, String - ID of organisation (if applicable to command)
- DatasetId, String - ID of dataset (if applicable to command)
- FileId, String - ID of file (if applicable to command)
- VersionId, String - ID of file version (if applicable to command)
- UserId - ID of user that who created the request
## Permissions

This API is accessible by authenticated users only:
- SuperAdmin should see operations awaiting approvals from all organisations on the platform.
- Organisation Admin should see operations awaiting approvals from their organisation only.
### SuperAdmin gets list of approvals

Given:
- I'm a SuperAdmin

When I request list of operations awaiting my approval,
Then I receive list of operations awaiting approval for all organisations on the platform; the list is paged according to $top and $skip parameters.
### Organisation Admin gets list of approvals

Given:
- I'm an Organisation Administrator

When I request list of operations awaiting my approval,

Then I receive list of operations awaiting approval for my organisation; the list is paged according to $top and $skip parameters.
## Standard HTTP REST API behaviour

The API follows standard HTTP REST APIs behaviour defined in NFR #891.
## Accept Criteria
- [ ] SuperAdmin will be able to retrieve the list of all operations awaiting approval in all organisations.
- [ ] Organisation Admin will be able to retrieve the list of all operations awaiting approval in their organisation only.

**Comment by adamamyl** [comment]
UI note:
- give those authorized to view this list (in CKAN), an ability to batch select items
- probably need some magic to translate IDs to names, especially on user, org, file, dataset

**Comment by adamamyl** [comment]
The approval/rejection action/API itself is defined in #93

**Comment by adamamyl** [comment]
Demo'd, and ready for testing.

**Comment by Nithyavasudevan** [comment]
works
