### ISSUE TITLE
US R9.2.1.3 As a SuperAdmin/OrganisationAdmin, I want to be able to download file content awaiting my approval, so I can view the file being published

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#92]
## Microsoft API

The data collection service should expose the following REST API:

`GET https://<HostURL>/Approval/<requestId>/download`

The successful response should stream the content of the file awaiting approval. Content-disposition header should be set, so that the suggested name of the downloaded file matches the file name.
## Permissions

This API is accessible by authenticated users only:
- SuperAdmin can download file content for file create and update operations awaiting approvals from all organisations on the platform.
- Organisation Admin can download file content for file create and update operations awaiting approvals from their organisation only.
### Successful download

Given:
- I have sufficient rights
- Operation with request ID ""X"" is pending approval,
- there is a file content associated with the operation

When I request to download the content of file awaiting my approval
Then I receive the file content; the response has Content-disposition header set with the name of the file.
### No file associated with the request

Given:
- I have sufficient rights
- Operation with request ID ""X"" is pending approval,
- there is no file content associated with the operation \* When I request to download the content of file awaiting my approval

Then I receive an error response response with HTTP status code 404
### Non-existing Request

Given:
- I have sufficient rights
- Operation with request ID ""X"" is not pending approval,

When I request to download the content of file awaiting my approval

Then I receive an error response response with HTTP status code 404
##  Standard HTTP REST API behaviour

The API follows standard HTTP REST APIs behaviour defined in NFR #891.
## Accept Criteria
- [ ] SuperAdmin will be able to download the content of files awaiting approval in all organisations, provided there is file content associated with the operation.
- [ ] Organisation Admin will be able to download the content of files awaiting approval in their organisation only, provided there is file content associated with the operation.

**Comment by adamamyl** [comment]
Demo'd, and ready for testing.

**Comment by Nithyavasudevan** [comment]
this seems to have broken. On download, I get an empty file and not the actual file content.I checked logged in as orgadmin and superadmin.
![image](https://cloud.githubusercontent.com/assets/7315913/4224669/1eb6ae86-3927-11e4-96a4-4194402f6843.png)

**Comment by amercader** [comment]
What are the original contents of the "coté.txt" file? At least some lines so we can check.

**Comment by amercader** [comment]
This is now fixed and ready for testing

**Comment by mcginns** [comment]
Re-tested successfully. This can be closed.

![image](https://cloud.githubusercontent.com/assets/7511445/4272681/8684b5d8-3ce4-11e4-88bf-bfc8e8bd4635.png)
