### ISSUE TITLE
US 1.2.5 As a SuperAdmin, Organisation Admin/Editor, I want to be able to initiate deletion of a specific version of a file, so I can remove it from the dataset.

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#94]
##  Microsoft API

Data Collection service will expose an HTTP REST API for file version deletion:

```
DELETE https://<hostUrl>/Files/Organisation/<organisationId>/Dataset/<datasetId>/File/<fileId>/Version/<versionId>
```

The successful response will contain a unique Request ID.

Only authenticated users can call this API:
- Organisation Admin/Editor can remove file versions from datasets from their organisation
- SuperAdmin can remove file versions form datasets from any organisation
### Successful submission

Given:
- I have suitable access rights (incl. check that specified organisationId matches the calling user's organisation - for Organisation Editor/Admin only)
- the request is well formed,

When I send a request to delete a specific file version
Then I receive a unique RequestID as JSON in the HTTP response with an HTTP Status 200 (OK)
### Organisation Editor/Admin deletes a file version from a different organisation

Given:
- I'm Organisation Editor/Admin belonding to organisation X
- I specify organisationId=Y

When I send a request to delete a file version,
Then my request is rejected and I receive a HTTP response with status 403 (Forbidden)
## Standard HTTP REST API behaviour

The API follows standard HTTP REST APIs behaviour defined in NFR #891.
##  Business rules (for info)
- Files are not physically removed. The metadata are marked as removed in Metadata DB and files content remains in the storage.
- Removed file versions are no longer visible in listings (get datasets, get files, etc.) and search. The removed file versions cannot be downloaded.
- Users cannot update deleted file versions - they are treated as if they didn't exist on the platform.
- If the latest file version is deleted, the previous version is treated as the latest. If the deleted version is the only version of the file, the whole file is treated as deleted.
## Accept Criteria

When I have suitable access rights, I can initiate deletion of a specific version of a file and I should receive a unique request ID.

**Comment by amercader** [comment]
According to the latest functional spec, file deletions (as well as dataset and organization ones) are "De-scoped Functionality"

> The following describes functionality that an agreed user stories and a design was created for, but the implementation of the functionality did not get included during the project build phase.

We can not implement it without this backend support

**Comment by adamamyl** [comment]
@stevenlivz is that a mistake in the Functional Spec, or is this out of scope, now?

**Comment by adamamyl** [comment]
Would have demo'd, but seems to be an issue with this being in/out of scope as Functional Spec has this as no longer built, and API returns an "operation not supported" type message.

**Comment by amercader** [comment]
Implemented in CKAN. Delete requests are sent but seem to get stucked with an "InProgress" status (already pinged MS about this). Once this is solved we can test the second half of the process, harvesting the changelog entry and delete the resource (this is already implemented in CKAN as well)

**Comment by adamamyl** [comment]
https://www.yammer.com/futurecitiesdemonstrator/#/Threads/show?threadId=430544530

**Comment by Nithyavasudevan** [comment]
Is this code in integration? I am aware the platform bit doesn't work yet, but if this code is in integration, i should still be able to check that the file got deleted on the platform

**Comment by amercader** [comment]
Deleting the latest version of a file (ie via the resource edit form) now works.

We still have to implement it for a particular version

**Comment by amercader** [comment]
This is now implemented. As part of the changeset we've improved the presentation of the file versions. There is now a button on the resource page to access the listing:

![mh5ochu](https://cloud.githubusercontent.com/assets/200230/4074316/e86f7c68-2e9f-11e4-8519-a533a83a4b50.png)

Once in the listing, authorized users will see a "Delete" button on each of the versions:

![pzd1cz9](https://cloud.githubusercontent.com/assets/200230/4075729/3eb56020-2eb3-11e4-8138-98ce74fa0fd1.png)

**Comment by stevenlivz** [comment]
Much better. Nice work :-)

-----Original Message-----

**Comment by Nithyavasudevan** [comment]
although this works for superadmin, cannot close this user story as need all users working before i can test this user story

**Comment by Nithyavasudevan** [comment]
removing ready for testing as creating superadmins from ckan not yet implemented and so dev team would not have actually tested permissions for this function. will wait until that is done.

**Comment by adamamyl** [comment]
Needs user roles and perms in place (see #53)

**Comment by amercader** [comment]
This feature is ready for testing. If it needs to be tested under certain conditions we can keep the issue open until these are met

**Comment by Nithyavasudevan** [comment]
tested as SuperADmin, OrgAdmin and OrgEditor. Works
