### ISSUE TITLE
Unable to update organisation as Org Admin

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#96]
1. Logged into ckan as i4admin@gccctpecadint.onmicrosoft.com
2. I4 Acceptance is the organisation i am an admin for
3. Went to organisation page
   https://ckanfrontend.cloudapp.net/organization/i4-acceptance
4. No link to actually update organisation.
   ![image](https://cloud.githubusercontent.com/assets/7315913/3797058/5338606c-1bd3-11e4-91fa-11c7d7134d98.png)

**Comment by adamamyl** [comment]
There are two 'Nithya Srinivas' users -- one's an editor, one's an org-admin. Could you check which Nithya Srinivas this happens under?

**Comment by Nithyavasudevan** [comment]
Update organisation is possible only by Superadmins and Org Admin.. Editors cannot update organisations..

**Comment by adamamyl** [comment]
This seems to just not be a case of the 'Manage' button for this type of user.

Going by URI seems to work.

**Comment by mcginns** [comment]
Updated Organisation details successfully as Org admin (admin2@open.glasgow.gov.uk) on Prod.

![image](https://cloud.githubusercontent.com/assets/7511445/4303855/3c129780-3e6b-11e4-8abe-2148ecf53fe6.png)

Pending changes tab operates as expected.
